/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.Execution.CanonicalBooleanProgram
import SparkInterval.Execution.ParsedCertificateProgram
import SparkInterval.Execution.ProjectedCertificateProgram
import SparkInterval.TernaryGoldbach.CDEMAbelArtifactProgram
import SparkInterval.TernaryGoldbach.CompactExternalAtomCapstone
import SparkInterval.TernaryGoldbach.RamareNativeFoldsCompactChecker

/-!
# Closed source-program audit for the external Goldbach campaigns

This file audits the ten physical campaigns serving the thirteen named
external atoms, plus the separately registered Ramaré three-fold fallback.
It asks a deliberately narrower question than whether a campaign has useful
Lean arithmetic:

* is there one closed, total `Bool` algorithm;
* is its input data either generated by a closed definition or parsed and
  bound to the exact reviewed artifact;
* and is there an ordinary theorem
  `check = true → nativeChecker.accepts canonicalInput canonicalResult`?

Descriptor-input programs may be represented by `ProgramStatus.concrete`.
Their program must be the input-gating `CanonicalBooleanProgram`.  Complete
artifact-input programs may instead be represented by
`ProgramStatus.artifactConcrete`; their program is constructed by
`ParsedCertificateProgram` from a total parser and Boolean checker.  Neither
form may call `nativeChecker.accepts`, and neither Boolean may take a
proposition, proof, or receipt as an argument.

The current audit finds one complete source boundary: the CDEM Abel artifact
program.  It parses the complete recurrence stream and proves its successful
Boolean replay implies the legacy source claim.  This does **not** prove that
the optimized C++, compiler, x86 executable, Azure VM, or receipt implements
that source program.  The other ten entries remain missing and record:

1. existing reusable algorithm/proof declarations;
2. the exact closed generator or embedded-data definition still needed;
3. the exact artifact parser and identity binding still needed;
4. the total campaign Boolean still needed; and
5. the final ordinary soundness theorem still needed.

The strings below are audit specifications only.  They neither create a Lean
declaration nor serve as a theorem premise.  This module defines no receipt,
source-scale evidence inhabitant, architecture run, or axiom, and it performs
no source-scale evaluation.
-/

set_option autoImplicit false

namespace SparkInterval.TernaryGoldbach.ClosedSourceProgramCatalog

open SparkInterval.Execution.Architecture
open SparkInterval.Execution.Architecture.DeterministicFinalizerIR

/-! ## Closed eleven-campaign audit roster -/

/-- Exactly the ten external campaigns and the one Ramaré fallback.

The native-generated aggregate is intentionally absent: its proposition and
decision procedure live in the downstream application package. -/
inductive Campaign where
  | ch25A7Boundary
  | ch25PsiLemma92
  | plattHead2e4
  | plattTrudgianRH3e12
  | helfgottProp1224
  | hurstSharedFourResidual
  | cdemTableAbel
  | ramareZunigaLemma62
  | helfgottPlattTheorem41
  | plattDirichletTheorem71
  | ramareProductionFolds
  deriving Repr, DecidableEq, BEq

namespace Campaign

/-- Exhaustive audit order: registry external campaigns followed by the sole
native-family fallback. -/
def all : List Campaign :=
  [.ch25A7Boundary, .ch25PsiLemma92, .plattHead2e4,
    .plattTrudgianRH3e12, .helfgottProp1224,
    .hurstSharedFourResidual, .cdemTableAbel,
    .ramareZunigaLemma62, .helfgottPlattTheorem41,
    .plattDirichletTheorem71, .ramareProductionFolds]

/-- Exact architecture invocation represented by an audited campaign. -/
def invocation : Campaign → RegisteredArchitectureInvocation
  | .ch25A7Boundary => .ch25A7BoundaryProductionV1
  | .ch25PsiLemma92 => .ch25PsiLemma92ProductionV1
  | .plattHead2e4 => .plattHead2e4ProductionV1
  | .plattTrudgianRH3e12 => .plattTrudgianFiniteRHProductionV1
  | .helfgottProp1224 => .helfgottProp1224ProductionV1
  | .hurstSharedFourResidual => .hurstSharedFourResidualProductionV2
  | .cdemTableAbel => .cdemTableAbelProductionV2
  | .ramareZunigaLemma62 => .ramareZunigaLemma62ProductionV1
  | .helfgottPlattTheorem41 => .helfgottPlattGoldbachProductionV1
  | .plattDirichletTheorem71 => .plattDirichletTheorem71ProductionV1
  | .ramareProductionFolds => .ramareProductionFoldsCompactV1

/-- Fixed checker selected by an audited campaign. -/
def checker : Campaign → NativeCheckerSemantics
  | .ch25A7Boundary => A7BoundaryCompactChecker.nativeChecker
  | .ch25PsiLemma92 => PsiCompactChecker.nativeChecker
  | .plattHead2e4 => ZetaHeadCompactChecker.nativeChecker
  | .plattTrudgianRH3e12 => ZetaRHCompactChecker.nativeChecker
  | .helfgottProp1224 => Prop1224CompactChecker.nativeChecker
  | .hurstSharedFourResidual => HurstCompactChecker.nativeChecker
  | .cdemTableAbel => CDEMAbelCompactChecker.nativeChecker
  | .ramareZunigaLemma62 => R2StarCompactChecker.nativeChecker
  | .helfgottPlattTheorem41 => GoldbachCompactChecker.nativeChecker
  | .plattDirichletTheorem71 =>
      SparkInterval.Dirichlet.PlattTheorem71CompactChecker.nativeChecker
  | .ramareProductionFolds =>
      RamareNativeFoldsCompactChecker.nativeChecker

/-- Exact canonical input selected by an audited campaign. -/
def canonicalInput : Campaign → ByteArray
  | .ch25A7Boundary => A7BoundaryCompactChecker.canonicalInputBytes
  | .ch25PsiLemma92 => PsiCompactChecker.canonicalInputBytes
  | .plattHead2e4 => ZetaHeadCompactChecker.canonicalInputBytes
  | .plattTrudgianRH3e12 => ZetaRHCompactChecker.canonicalInputBytes
  | .helfgottProp1224 => Prop1224CompactChecker.canonicalInputBytes
  | .hurstSharedFourResidual => HurstCompactChecker.canonicalInputBytes
  | .cdemTableAbel => CDEMAbelCompactChecker.canonicalInputBytes
  | .ramareZunigaLemma62 => R2StarCompactChecker.canonicalInputBytes
  | .helfgottPlattTheorem41 => GoldbachCompactChecker.canonicalInputBytes
  | .plattDirichletTheorem71 =>
      SparkInterval.Dirichlet.PlattTheorem71CompactChecker.canonicalInputBytes
  | .ramareProductionFolds =>
      RamareNativeFoldsCompactChecker.canonicalInputBytes

/-- Exact canonical result selected by an audited campaign. -/
def canonicalResult : Campaign → ByteArray
  | .ch25A7Boundary => A7BoundaryCompactChecker.canonicalResultBytes
  | .ch25PsiLemma92 => PsiCompactChecker.canonicalResultBytes
  | .plattHead2e4 => ZetaHeadCompactChecker.canonicalResultBytes
  | .plattTrudgianRH3e12 => ZetaRHCompactChecker.canonicalResultBytes
  | .helfgottProp1224 => Prop1224CompactChecker.canonicalResultBytes
  | .hurstSharedFourResidual => HurstCompactChecker.canonicalResultBytes
  | .cdemTableAbel => CDEMAbelCompactChecker.canonicalResultBytes
  | .ramareZunigaLemma62 => R2StarCompactChecker.canonicalResultBytes
  | .helfgottPlattTheorem41 => GoldbachCompactChecker.canonicalResultBytes
  | .plattDirichletTheorem71 =>
      SparkInterval.Dirichlet.PlattTheorem71CompactChecker.canonicalResultBytes
  | .ramareProductionFolds =>
      RamareNativeFoldsCompactChecker.canonicalResultBytes

end Campaign

/-! ## Status data -/

/-- Human-auditable missing pieces for one campaign.

Each required field is written as a declaration-shaped specification, rather
than a vague project note.  `existingPieces` prevents a useful inner checker
from being confused with the still-missing closed finalizer. -/
structure MissingProgramClassification where
  existingPieces : List String
  requiredGenerator : String
  requiredParser : String
  requiredTotalCheck : String
  requiredSoundness : String
  deriving Repr, DecidableEq

/-- A reviewed closed Boolean program.

The equality forces the source program itself to be the generic canonical
input gate around one closed Boolean.  In particular, a future concrete entry
cannot define its run function by invoking the propositional acceptance
relation. -/
structure ConcreteProgram (campaign : Campaign) where
  check : Bool
  certificate : Certificate campaign.checker
  canonicalProgram :
    certificate.program =
      SparkInterval.Execution.Architecture.CanonicalBooleanProgram.program
        campaign.checker campaign.canonicalInput
          campaign.canonicalResult check

/-- A reviewed complete-artifact source program.

The fields expose the data type, parser, and Boolean instead of storing an
arbitrary deterministic-program certificate.  `certificate` below is always
constructed by the generic parsed-certificate program, so its successful
branch cannot call the propositional checker relation.  `legacyAcceptance`
is the ordinary theorem which connects the stronger artifact-input checker
to the existing descriptor-input campaign checker. -/
structure ArtifactConcreteProgram (campaign : Campaign) where
  CertificateData : Type
  artifactChecker : NativeCheckerSemantics
  decode : ByteArray → Option CertificateData
  check : CertificateData → Bool
  successResult : ByteArray
  sound :
    SparkInterval.Execution.Architecture.ParsedCertificateProgram.ParseCheckSound
      artifactChecker decode check successResult
  legacyAcceptance :
    ∀ {inputBytes outputBytes : ByteArray},
      artifactChecker.accepts inputBytes outputBytes →
        campaign.checker.accepts
          campaign.canonicalInput campaign.canonicalResult

namespace ArtifactConcreteProgram

/-- The only source certificate admitted by an artifact-concrete entry. -/
def certificate
    {campaign : Campaign}
    (program : ArtifactConcreteProgram campaign) :
    Certificate program.artifactChecker :=
  SparkInterval.Execution.Architecture.ParsedCertificateProgram.certificate
    program.artifactChecker program.decode program.check
      program.successResult program.sound

/-- Package the exact artifact program for architecture refinement while
keeping the fixed legacy checker projection separate from the measured
artifact input. -/
def projectedCertificate
    {campaign : Campaign}
    (program : ArtifactConcreteProgram campaign) :
    SparkInterval.Execution.Architecture.ProjectedCertificateProgram.Certificate
      program.artifactChecker campaign.checker where
  sourceProgram := program.certificate
  downstreamInput := campaign.canonicalInput
  downstreamResult := campaign.canonicalResult
  project := program.legacyAcceptance

end ArtifactConcreteProgram

/-- Current source-program availability for an exact campaign. -/
inductive ProgramStatus (campaign : Campaign) where
  | concrete (program : ConcreteProgram campaign)
  | artifactConcrete (program : ArtifactConcreteProgram campaign)
  | missing (classification : MissingProgramClassification)

/-! ## Per-campaign missing-program specifications -/

/-- Exact missing boundary found by the A.7 campaign audit. -/
def a7Missing : MissingProgramClassification where
  existingPieces :=
    ["A7BoundaryCertificate.Certificate.check",
      "A7BoundaryCertificate.Certificate.accepted_of_check_eq_true",
      "A7BoundaryCertificate.sourceClaim_of_checked_certificate",
      "A7BoundaryWire.parse",
      "A7BoundaryWire.checkRetainedBytes",
      "A7BoundaryWire.checkRetainedBytes_sound"]
  requiredGenerator :=
    "a7CanonicalCertificate : A7BoundaryCertificate.Certificate, plus a \
data-only analytic-enclosure certificate for the same transcript"
  requiredParser :=
    "decodeA7AnalyticArtifact : ByteArray → Option A7AnalyticCertificate. \
The finite seven-field transcript already has an exact retained-identity \
parser in A7BoundaryWire; the absent parser is specifically for a data-only \
analytic-enclosure realization with exact row binding"
  requiredTotalCheck :=
    "a7FinalCheck : A7BoundaryCertificate.Certificate → \
A7AnalyticCertificate → Bool, combining Certificate.check with the \
analytic-enclosure replay"
  requiredSoundness :=
    "a7FinalCheck a7CanonicalCertificate a7CanonicalAnalytic = true → \
A7BoundaryCompactChecker.nativeChecker.accepts \
A7BoundaryCompactChecker.canonicalInputBytes \
A7BoundaryCompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the psi campaign audit. -/
def psiMissing : MissingProgramClassification where
  existingPieces :=
    ["PsiPrimePowerCertificate.sourceClaim_of_gap_evidence",
      "PsiSourceSemantics.lowerEndpointSafe_real",
      "PsiSourceSemantics.upperEndpointSafe_real"]
  requiredGenerator :=
    "psiCanonicalGapCertificate : PsiGapCertificate, where \
PsiGapCertificate is data-only and contains every directed log row and \
prime-power gap through 10^13"
  requiredParser :=
    "decodePsiArtifact : ByteArray → Option PsiGapCertificate, with exact \
campaign-range and artifact-identity binding"
  requiredTotalCheck :=
    "psiGapCheck : PsiGapCertificate → Bool, checking directed-log \
realization, event-gap coverage, state constancy, and both endpoint guards"
  requiredSoundness :=
    "psiGapCheck psiCanonicalGapCertificate = true → \
PsiCompactChecker.nativeChecker.accepts \
PsiCompactChecker.canonicalInputBytes \
PsiCompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the Platt zeta-head campaign audit. -/
def zetaHeadMissing : MissingProgramClassification where
  existingPieces :=
    ["ZetaHeadSourceSemantics.Q128CellTable.commitment",
      "SparkInterval.Zeta.RationalBracketFamily.check",
      "ZetaHeadSourceSemantics.q128SourceClaim_of_checked_evidence"]
  requiredGenerator :=
    "zetaHeadCanonicalCertificate : ZetaHeadFinalizerCertificate, containing \
all 22491 Q128 rows, endpoint enclosures, and multiplicity-aware Turing data"
  requiredParser :=
    "decodeZetaHeadArtifact : ByteArray → Option \
ZetaHeadFinalizerCertificate, with exact row-payload and commitment binding"
  requiredTotalCheck :=
    "zetaHeadFinalCheck : ZetaHeadFinalizerCertificate → Bool, checking the \
Q128 commitment, ordered Hardy-Z brackets, endpoint enclosures, and complete \
multiplicity count"
  requiredSoundness :=
    "zetaHeadFinalCheck zetaHeadCanonicalCertificate = true → \
ZetaHeadCompactChecker.nativeChecker.accepts \
ZetaHeadCompactChecker.canonicalInputBytes \
ZetaHeadCompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the finite-RH campaign audit. -/
def zetaRHMissing : MissingProgramClassification where
  existingPieces :=
    ["SparkInterval.Zeta.RationalEndpointChunk.check",
      "SparkInterval.Zeta.checkEndpointChunkStream",
      "SparkInterval.Zeta.checkEndpointChunkStream_sound",
      "ZetaRHSourceSemantics.sourceClaim_of_evidence"]
  requiredGenerator :=
    "zetaRHCanonicalCertificate : ZetaRHFinalizerCertificate, containing the \
complete chunk stream and multiplicity-aware global Turing certificate \
through 3000175332800"
  requiredParser :=
    "decodeZetaRHArtifact : ByteArray → Option ZetaRHFinalizerCertificate, \
with gap-free chunk ordering and exact source-height binding"
  requiredTotalCheck :=
    "zetaRHFinalCheck : ZetaRHFinalizerCertificate → Bool, combining chunk \
checks, analytic endpoint-enclosure checks, and the global count"
  requiredSoundness :=
    "zetaRHFinalCheck zetaRHCanonicalCertificate = true → \
ZetaRHCompactChecker.nativeChecker.accepts \
ZetaRHCompactChecker.canonicalInputBytes \
ZetaRHCompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the Proposition 12.2.4 campaign audit. -/
def prop1224Missing : MissingProgramClassification where
  existingPieces :=
    ["Prop1224SourceSemantics.Certificate.check",
      "Prop1224SourceSemantics.Certificate.checker_sound",
      "Prop1224SourceSemantics.sourceClaim_of_checked_certificate"]
  requiredGenerator :=
    "prop1224CanonicalCertificate : Prop1224FinalizerCertificate, containing \
the full shard chain and data-only MPFR/GMP row enclosures"
  requiredParser :=
    "decodeProp1224Artifact : ByteArray → Option \
Prop1224FinalizerCertificate, with rank interval and shard identity binding"
  requiredTotalCheck :=
    "prop1224FinalCheck : Prop1224FinalizerCertificate → Bool, combining the \
existing shard-chain check with every MPFR/GMP realization and row guard"
  requiredSoundness :=
    "prop1224FinalCheck prop1224CanonicalCertificate = true → \
Prop1224CompactChecker.nativeChecker.accepts \
Prop1224CompactChecker.canonicalInputBytes \
Prop1224CompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the shared Hurst campaign audit. -/
def hurstMissing : MissingProgramClassification where
  existingPieces :=
    ["HurstAffineCertificate.Certificate.check",
      "HurstAffineCertificate.Certificate.checker_sound",
      "HurstSourceSemantics.checked_shared_real_source_claims_of_local"]
  requiredGenerator :=
    "hurstCanonicalCertificate : HurstFinalizerCertificate, containing the \
full affine block chain and data-only local Mobius/Q96 replay rows"
  requiredParser :=
    "decodeHurstArtifact : ByteArray → Option HurstFinalizerCertificate, \
with exact source range, zero state, and block-stream identity binding"
  requiredTotalCheck :=
    "hurstFinalCheck : HurstFinalizerCertificate → Bool, combining the \
affine-chain check with every local row-delta and interval guard"
  requiredSoundness :=
    "hurstFinalCheck hurstCanonicalCertificate = true → \
HurstCompactChecker.nativeChecker.accepts \
HurstCompactChecker.canonicalInputBytes \
HurstCompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the Ramaré--Zúñiga campaign audit. -/
def r2StarMissing : MissingProgramClassification where
  existingPieces :=
    ["R2StarSourceSemantics.Certificate.check",
      "R2StarSourceSemantics.Certificate.checker_sound",
      "R2StarSourceSemantics.sourceClaim_of_checked_certificate"]
  requiredGenerator :=
    "r2StarCanonicalCertificate : R2StarFinalizerCertificate, containing the \
complete chunk chain and data-only factor-support/logarithm realization rows"
  requiredParser :=
    "decodeR2StarArtifact : ByteArray → Option R2StarFinalizerCertificate, \
with exact range, initial state, and chunk identity binding"
  requiredTotalCheck :=
    "r2StarFinalCheck : R2StarFinalizerCertificate → Bool, combining the \
chain checker with coefficient, directed-log, and endpoint-guard replay"
  requiredSoundness :=
    "r2StarFinalCheck r2StarCanonicalCertificate = true → \
R2StarCompactChecker.nativeChecker.accepts \
R2StarCompactChecker.canonicalInputBytes \
R2StarCompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the Helfgott--Platt Goldbach audit. -/
def goldbachMissing : MissingProgramClassification where
  existingPieces :=
    ["GoldbachSourceSemantics.PrimeLadder.check",
      "GoldbachSourceSemantics.PrimeLadder.check_sound",
      "GoldbachSourceSemantics.sourceClaim_of_checked_evidence"]
  requiredGenerator :=
    "goldbachCanonicalCertificate : GoldbachFinalizerCertificate, containing \
the binary-Goldbach aggregate and the complete finite prime ladder"
  requiredParser :=
    "decodeGoldbachArtifacts : ByteArray → Option \
GoldbachFinalizerCertificate, authenticating and binding both registered \
child artifact streams"
  requiredTotalCheck :=
    "goldbachFinalCheck : GoldbachFinalizerCertificate → Bool, combining a \
binary-Goldbach certificate checker with PrimeLadder.check and all range \
bindings"
  requiredSoundness :=
    "goldbachFinalCheck goldbachCanonicalCertificate = true → \
GoldbachCompactChecker.nativeChecker.accepts \
GoldbachCompactChecker.canonicalInputBytes \
GoldbachCompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the Platt Dirichlet campaign audit. -/
def plattDirichletMissing : MissingProgramClassification where
  existingPieces :=
    ["FactoredSmallQRawCompletedSignPayloadModulusCampaign.Certificate.check",
      "FactoredSmallQRawCompletedSignPayloadModulusCampaign.Certificate.checker_sound",
      "FactoredSmallQRosterGRHBridge.grhVerifiedForModulus_of_primitiveRosterCompletedSignBracketFamilies_of_two_le",
      "SparkInterval.Dirichlet.plattTheorem71_of_source_evidence"]
  requiredGenerator :=
    "platt71CanonicalCertificate : Platt71FinalizerCertificate, containing \
both parity rosters for every modulus 2 through 400000 and the bound q=1 \
zeta result"
  requiredParser :=
    "decodePlatt71Artifacts : ByteArray → Option \
Platt71FinalizerCertificate, authenticating all CPU/H100 child artifacts and \
binding modulus, character, parity, and source height"
  requiredTotalCheck :=
    "platt71FinalCheck : Platt71FinalizerCertificate → Bool, aggregating the \
factored-small-q raw checks, roster completeness, character enumeration, and \
q=1 zeta branch"
  requiredSoundness :=
    "platt71FinalCheck platt71CanonicalCertificate = true → \
PlattTheorem71CompactChecker.nativeChecker.accepts \
PlattTheorem71CompactChecker.canonicalInputBytes \
PlattTheorem71CompactChecker.canonicalResultBytes"

/-- Exact missing boundary found by the three-fold Ramaré fallback audit. -/
def ramareFoldsMissing : MissingProgramClassification where
  existingPieces :=
    ["RamareNativeFoldContracts.ScaledIntervalFold.realizes",
      "RamareNativeFoldContracts.sourceClaims_of_finiteFoldEvidence"]
  requiredGenerator :=
    "ramareFoldsCanonicalCertificate : RamareFoldsFinalizerCertificate, \
containing data-only interval states and increments for the 100M/100M/140M \
folds"
  requiredParser :=
    "decodeRamareFoldsArtifact : ByteArray → Option \
RamareFoldsFinalizerCertificate, with all three ranges, scales, and terminal \
states bound to the registered campaign"
  requiredTotalCheck :=
    "ramareFoldsFinalCheck : RamareFoldsFinalizerCertificate → Bool, checking \
all three recurrences, local increment realizations, and integer guards"
  requiredSoundness :=
    "ramareFoldsFinalCheck ramareFoldsCanonicalCertificate = true → \
RamareNativeFoldsCompactChecker.nativeChecker.accepts \
RamareNativeFoldsCompactChecker.canonicalInputBytes \
RamareNativeFoldsCompactChecker.canonicalResultBytes"

/-! ## Closed audit result -/

/-- The complete CDEM artifact-input source boundary.

This value contains no production artifact and no machine refinement.  It
states only that the exact total parser/Boolean source program is present and
that successful artifact checking implies the legacy campaign acceptance. -/
def cdemAbelConcrete :
    ArtifactConcreteProgram Campaign.cdemTableAbel where
  CertificateData := CDEMAbelArtifactProgram.Recurrence.Certificate
  artifactChecker := CDEMAbelArtifactProgram.artifactNativeChecker
  decode := CDEMAbelArtifactProgram.decode
  check := CDEMAbelClosedReplay.check
  successResult := CDEMAbelCompactChecker.canonicalResultBytes
  sound := CDEMAbelArtifactProgram.parseCheckSound
  legacyAcceptance := by
    intro inputBytes outputBytes accepted
    exact
      CDEMAbelArtifactProgram.legacy_accepts_of_artifact_acceptance
        accepted

/-- Current closed catalog.  CDEM has a complete artifact-input source
program.  Every other campaign remains fail closed with an explicit gap. -/
def status : (campaign : Campaign) → ProgramStatus campaign
  | .ch25A7Boundary => .missing a7Missing
  | .ch25PsiLemma92 => .missing psiMissing
  | .plattHead2e4 => .missing zetaHeadMissing
  | .plattTrudgianRH3e12 => .missing zetaRHMissing
  | .helfgottProp1224 => .missing prop1224Missing
  | .hurstSharedFourResidual => .missing hurstMissing
  | .cdemTableAbel => .artifactConcrete cdemAbelConcrete
  | .ramareZunigaLemma62 => .missing r2StarMissing
  | .helfgottPlattTheorem41 => .missing goldbachMissing
  | .plattDirichletTheorem71 => .missing plattDirichletMissing
  | .ramareProductionFolds => .missing ramareFoldsMissing

/-- Decidable projection used only to summarize this closed catalog. -/
def isConcrete (campaign : Campaign) : Bool :=
  match status campaign with
  | .concrete _ => true
  | .artifactConcrete _ => true
  | .missing _ => false

/-- The audit roster is exactly the registry's ten external campaigns plus
its sole Ramaré native-family fallback. -/
theorem invocationRoster_exact :
    Campaign.all.map Campaign.invocation =
      RegisteredArchitectureInvocation.externalCampaigns ++
        RegisteredArchitectureInvocation.nativeFamilyFallbacks := by
  rfl

/-- The bounded audit covers exactly eleven physical campaigns. -/
theorem auditedCampaignCount : Campaign.all.length = 11 := by
  rfl

/-- CDEM is source-program complete at the full artifact boundary. -/
theorem cdemAbel_status_concrete :
    status Campaign.cdemTableAbel =
      .artifactConcrete cdemAbelConcrete := by
  rfl

/-- Every campaign other than CDEM remains missing. -/
theorem noConcreteCampaign
    (campaign : Campaign)
    (notCDEM : campaign ≠ Campaign.cdemTableAbel) :
    isConcrete campaign = false := by
  cases campaign <;> simp_all [isConcrete, status]

/-- Exact source-program-complete roster. -/
theorem concreteCampaigns :
    Campaign.all.filter isConcrete = [.cdemTableAbel] := by
  rfl

/-- Machine-checkable summary of the current audit result. -/
theorem concreteCampaignCount :
    (Campaign.all.filter isConcrete).length = 1 := by
  rfl

end SparkInterval.TernaryGoldbach.ClosedSourceProgramCatalog
