/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.TernaryGoldbach.HurstPrefixCandidateReduction

/-!
# Cheap terminal invariants for Möbius/Hurst receipts

The host receipt finalizer can reject impossible device summaries before
hashing them.  This file proves the corresponding source-level checks:

* the terminal Mertens delta has absolute value at most the squarefree count;
* the squarefree count is at most the actual leaf length;
* Mertens and squarefree deltas have the same parity; and
* an integer/right-limit candidate generated by an actual leaf has order
  strictly below twice that leaf's length.

These are necessary sanity checks, not a replacement for refining the
compiled CUDA computation to the exact row stream.
-/

set_option autoImplicit false

namespace SparkInterval.TernaryGoldbach.HurstAffineTerminalInvariants

open SparkInterval.TernaryGoldbach.HurstPrefixCandidateReduction
open SparkInterval.TernaryGoldbach.HurstAffineCandidateFilter

/-- Exact inexpensive arithmetic checks available to a receipt parser. -/
def TerminalDeltaValid (rowCount : Nat) (delta : PrefixMQ) : Prop :=
  -((delta.squarefree : Nat) : Int) ≤ delta.mertens ∧
    delta.mertens ≤ (delta.squarefree : Int) ∧
    delta.squarefree ≤ rowCount ∧
    (delta.mertens + (delta.squarefree : Int)) % 2 = 0

private theorem validRow_mertens_between_squarefree
    {row : PrefixMQ} (valid : PrefixInputRowValid row) :
    -((row.squarefree : Nat) : Int) ≤ row.mertens ∧
      row.mertens ≤ (row.squarefree : Int) := by
  rcases valid with ⟨lower, upper, squarefree⟩
  by_cases zero : row.mertens = 0
  · simp [zero] at squarefree
    omega
  · simp [zero] at squarefree
    omega

private theorem validRow_parity
    {row : PrefixMQ} (valid : PrefixInputRowValid row) :
    (row.mertens + (row.squarefree : Int)) % 2 = 0 := by
  rcases valid with ⟨lower, upper, squarefree⟩
  by_cases zero : row.mertens = 0
  · simp [zero] at squarefree
    simp [zero, squarefree]
  · simp [zero] at squarefree
    have sign : row.mertens = -1 ∨ row.mertens = 1 := by
      omega
    rcases sign with sign | sign <;> simp [sign, squarefree]

/-- Every valid direct-row stream satisfies all terminal delta checks. -/
theorem inputTotal_terminalDeltaValid
    {rows : List PrefixMQ} (valid : PrefixInputRowsValid rows) :
    TerminalDeltaValid rows.length (inputTotal rows) := by
  induction rows with
  | nil =>
      simp [TerminalDeltaValid, inputTotal]
  | cons row rest inductionHypothesis =>
      have rowValid : PrefixInputRowValid row :=
        valid row (by simp)
      have restValid : PrefixInputRowsValid rest := by
        intro other member
        exact valid other (by simp [member])
      have rowBounds :=
        validRow_mertens_between_squarefree rowValid
      have rowParity := validRow_parity rowValid
      have rowCount : row.squarefree ≤ 1 := by
        rw [rowValid.2.2]
        split <;> omega
      have restInvariant := inductionHypothesis restValid
      rcases restInvariant with
        ⟨restLower, restUpper, restCount, restParity⟩
      unfold TerminalDeltaValid
      simp only [inputTotal, PrefixMQ.add_mertens,
        PrefixMQ.add_squarefree, List.length_cons, Nat.cast_add]
      constructor
      · omega
      constructor
      · omega
      constructor
      · omega
      · rw [show
          row.mertens + (inputTotal rest).mertens +
              ((row.squarefree : Int) +
                ((inputTotal rest).squarefree : Int)) =
            (row.mertens + (row.squarefree : Int)) +
              ((inputTotal rest).mertens +
                ((inputTotal rest).squarefree : Int)) by
            ring]
        rw [Int.add_emod, rowParity, restParity]
        norm_num

/-- Expanded form used directly by a fixed-width host validator. -/
theorem inputTotal_host_sanity_checks
    {rows : List PrefixMQ} (valid : PrefixInputRowsValid rows) :
    -(((inputTotal rows).squarefree : Nat) : Int) ≤
        (inputTotal rows).mertens ∧
      (inputTotal rows).mertens ≤
        ((inputTotal rows).squarefree : Int) ∧
      (inputTotal rows).squarefree ≤ rows.length ∧
      ((inputTotal rows).mertens +
          ((inputTotal rows).squarefree : Int)) % 2 = 0 :=
  inputTotal_terminalDeltaValid valid

/-- A native integer/right-limit order produced by an actual leaf is bounded
by that leaf, not merely by the global 100-million-row cap. -/
theorem rowCandidate_order_lt_twice_actual_length
    {value : Nat → PrefixMQ → Int} {endpoint : Nat}
    {prefixes : List PrefixMQ} {candidate : OrderedCandidate}
    (endpointBound : endpoint ≤ 1)
    (member : candidate ∈ rowCandidates value endpoint prefixes) :
    candidate.order < 2 * prefixes.length := by
  rw [mem_rowCandidates_iff] at member
  rcases member with ⟨index, inRange, rfl⟩
  change 2 * index + endpoint < 2 * prefixes.length
  omega

/-- The same actual-leaf bound for the paired endpoint stream used by the
squarefree guard. -/
theorem pairedEndpointCandidate_order_lt_twice_actual_length
    {integerValue rightValue : Nat → PrefixMQ → Int}
    {includeRight : Nat → Bool}
    {prefixes : List PrefixMQ} {candidate : OrderedCandidate}
    (member :
      candidate ∈ pairedEndpointCandidates
        integerValue rightValue includeRight prefixes) :
    candidate.order < 2 * prefixes.length := by
  rcases mem_pairedEndpointCandidates member with
      integerMember | rightMember
  · exact rowCandidate_order_lt_twice_actual_length
      (by omega) integerMember
  · exact rowCandidate_order_lt_twice_actual_length
      (by omega) rightMember

/-- Every local prefix witness is bounded by the terminal squarefree delta. -/
theorem inputPrefixAt_squarefree_le_inputTotal
    (rows : List PrefixMQ) (count : Nat) :
    (inputPrefixAt rows count).squarefree ≤
      (inputTotal rows).squarefree := by
  have split :
      inputTotal rows =
        inputTotal (rows.take count) +
          inputTotal (rows.drop count) := by
    conv_lhs => rw [← List.take_append_drop count rows]
    exact inputTotal_append _ _
  rw [inputPrefixAt, split]
  simp only [PrefixMQ.add_squarefree]
  omega

#print axioms inputTotal_terminalDeltaValid
#print axioms inputTotal_host_sanity_checks
#print axioms rowCandidate_order_lt_twice_actual_length
#print axioms pairedEndpointCandidate_order_lt_twice_actual_length
#print axioms inputPrefixAt_squarefree_le_inputTotal

end SparkInterval.TernaryGoldbach.HurstAffineTerminalInvariants
