/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.TernaryGoldbach.MobiusSegmentEventEnumeration

/-!
# Exact block/thread realization of residue-seeded Möbius events

The optimized dense CUDA pass uses one rectangular collection of block slots
per prime.  Inside a slot, thread `t` visits event ordinals

```
block * eventsPerBlock + t + iteration * threadsPerBlock.
```

`MobiusSegmentEventEnumeration` proves that the prime-event progression
enumerates every divisible segment row exactly once.  This file closes the
next architecture-independent layer: at the public segment cap and for every
residue-seeded suffix prime `p ≥ 7`, each divisible row has exactly one legal
block/thread/iteration visit in the proved 147-slot minimum schedule.

The theorem is about natural-number launch geometry.  It does not identify
CUDA registers, control flow, or machine execution with these definitions.
-/

set_option autoImplicit false

namespace SparkInterval.TernaryGoldbach.MobiusDenseVisitRealization

open SparkInterval.TernaryGoldbach.MobiusDenseSchedule
open SparkInterval.TernaryGoldbach.MobiusSegmentEventEnumeration

/-- One coordinate in the rectangular dense-prime CUDA schedule. -/
structure DenseVisit where
  block : Nat
  thread : Nat
  iteration : Nat
deriving DecidableEq, Repr

/-- Global prime-event ordinal generated by one dense schedule coordinate. -/
def DenseVisit.event (visit : DenseVisit) : Nat :=
  eventBegin visit.block +
    (visit.iteration * threadsPerBlock + visit.thread)

/-- A coordinate is a legal visit to `offset` in the clipped CUDA event
interval for one prime. -/
def Visits
    (count first prime offset : Nat) (visit : DenseVisit) : Prop :=
  visit.block < residueMinimumBlockSlotsPerPrime ∧
    visit.thread < threadsPerBlock ∧
    visit.iteration < iterationsPerThread ∧
    visit.event < eventStop
      (multipleEventCount count first prime) visit.block ∧
    multipleOffset first prime visit.event = offset

/-- The canonical block/thread/iteration coordinate of an event ordinal. -/
def ownerVisit (event : Nat) : DenseVisit where
  block := eventOwner event
  thread := threadOwner (eventLocal event)
  iteration := iterationOwner (eventLocal event)

@[simp] theorem ownerVisit_event (event : Nat) :
    (ownerVisit event).event = event := by
  exact event_block_thread_decode event

theorem eventOwner_lt_of_capacity
    {slots eventCount event : Nat}
    (capacity :
      eventCount ≤ slots * eventsPerBlock)
    (eventInRange : event < eventCount) :
    eventOwner event < slots := by
  rw [eventOwner, Nat.div_lt_iff_lt_mul]
  · exact lt_of_lt_of_le eventInRange capacity
  · norm_num [eventsPerBlock, threadsPerBlock, iterationsPerThread]

theorem ownerVisit_visits
    {lower count offset prime event : Nat}
    (countBound : count ≤ maximumSegmentRows)
    (primeBound : residueSuffixMinimumPrime ≤ prime)
    (eventInRange :
      event <
        multipleEventCount count (firstOffset lower prime) prime)
    (eventOffset :
      multipleOffset (firstOffset lower prime) prime event = offset) :
    Visits count (firstOffset lower prime) prime offset
      (ownerVisit event) := by
  have capacity :
      multipleEventCount count (firstOffset lower prime) prime ≤
        residueMinimumBlockSlotsPerPrime * eventsPerBlock :=
    residueMultipleEventCount_le_minimumCapacity countBound primeBound
  have localBound :
      eventLocal event < eventsPerBlock :=
    Nat.mod_lt _ (by
      norm_num [eventsPerBlock, threadsPerBlock, iterationsPerThread])
  have ownerMembership :=
    event_mem_owner eventInRange
  refine ⟨?_, threadOwner_lt _, iterationOwner_lt localBound, ?_, ?_⟩
  · exact eventOwner_lt_of_capacity
      capacity eventInRange
  · change (ownerVisit event).event <
      eventStop
        (multipleEventCount count (firstOffset lower prime) prime)
        (eventOwner event)
    rw [ownerVisit_event]
    exact ownerMembership.2
  · simpa using eventOffset

/-- Any legal dense coordinate visiting a fixed offset has the canonical
event coordinate. -/
theorem visit_eq_ownerVisit
    {count first prime offset event : Nat}
    (primePositive : 0 < prime)
    (eventOffset :
      multipleOffset first prime event = offset)
    {visit : DenseVisit}
    (visitValid : Visits count first prime offset visit) :
    visit = ownerVisit event := by
  have visitEventEq :
      visit.event = event :=
    multipleOffset_injective primePositive
      (visitValid.2.2.2.2.trans eventOffset.symm)
  have visitBegin :
      eventBegin visit.block ≤ visit.event := by
    simp [DenseVisit.event]
  have visitStop :
      visit.event <
        eventBegin visit.block + eventsPerBlock := by
    have clipped :
        eventStop
            (multipleEventCount count first prime) visit.block ≤
          eventBegin visit.block + eventsPerBlock := by
      simp [eventStop]
    exact lt_of_lt_of_le visitValid.2.2.2.1 clipped
  have blockEq :
      visit.block = eventOwner event := by
    rw [← visitEventEq]
    exact block_eq_eventOwner visitBegin visitStop
  have localEq :
      visit.iteration * threadsPerBlock + visit.thread =
        iterationOwner (eventLocal event) * threadsPerBlock +
          threadOwner (eventLocal event) := by
    have expanded :
        eventBegin visit.block +
            (visit.iteration * threadsPerBlock + visit.thread) =
          event := by
      simpa [DenseVisit.event] using visitEventEq
    have sameBegin :
        eventBegin visit.block +
            (visit.iteration * threadsPerBlock + visit.thread) =
          eventBegin visit.block +
            (iterationOwner (eventLocal event) * threadsPerBlock +
              threadOwner (eventLocal event)) := by
      calc
        eventBegin visit.block +
              (visit.iteration * threadsPerBlock + visit.thread) =
            event := expanded
        _ = eventBegin (eventOwner event) +
              (iterationOwner (eventLocal event) * threadsPerBlock +
                threadOwner (eventLocal event)) :=
          (event_block_thread_decode event).symm
        _ = eventBegin visit.block +
              (iterationOwner (eventLocal event) * threadsPerBlock +
                threadOwner (eventLocal event)) := by
          rw [blockEq]
    exact Nat.add_left_cancel sameBegin
  have threadEq :
      visit.thread = threadOwner (eventLocal event) := by
    have visitThreadBound := visitValid.2.1
    have ownerThreadBound := threadOwner_lt (eventLocal event)
    norm_num [threadsPerBlock] at localEq visitThreadBound ownerThreadBound ⊢
    omega
  have iterationEq :
      visit.iteration =
        iterationOwner (eventLocal event) := by
    have visitThreadBound := visitValid.2.1
    have ownerThreadBound := threadOwner_lt (eventLocal event)
    norm_num [threadsPerBlock] at localEq visitThreadBound ownerThreadBound ⊢
    omega
  cases visit
  simp_all [ownerVisit]

/-- Exact dense-schedule theorem.  Every in-segment row is divisible by the
residue-seeded suffix prime iff exactly one legal block/thread/iteration
coordinate visits it. -/
theorem dvd_iff_existsUnique_denseVisit
    {lower count offset prime : Nat}
    (countBound : count ≤ maximumSegmentRows)
    (primeBound : residueSuffixMinimumPrime ≤ prime)
    (offsetInSegment : offset < count) :
    prime ∣ lower + offset ↔
      ∃! visit, Visits count (firstOffset lower prime) prime offset visit := by
  have primePositive : 0 < prime := by
    have suffixPositive : 0 < residueSuffixMinimumPrime := by
      norm_num [residueSuffixMinimumPrime]
    omega
  constructor
  · intro divides
    have eventUnique :=
      (dvd_iff_existsUnique_event primePositive offsetInSegment).mp
        divides
    rcases eventUnique with ⟨event, eventFacts, _⟩
    refine ⟨ownerVisit event, ?_, ?_⟩
    · exact ownerVisit_visits countBound primeBound
        eventFacts.1 eventFacts.2
    · intro visit visitValid
      exact visit_eq_ownerVisit primePositive eventFacts.2 visitValid
  · rintro ⟨visit, visitValid, _⟩
    rw [← visitValid.2.2.2.2]
    exact dvd_multipleOffset lower
      (firstOffset lower prime) prime visit.event
      (firstOffset_dvd lower primePositive)

#print axioms ownerVisit_event
#print axioms eventOwner_lt_of_capacity
#print axioms ownerVisit_visits
#print axioms visit_eq_ownerVisit
#print axioms dvd_iff_existsUnique_denseVisit

end SparkInterval.TernaryGoldbach.MobiusDenseVisitRealization
