/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.TernaryGoldbach.MobiusFusedFinalization
import SparkInterval.TernaryGoldbach.MobiusSegmentEventEnumeration

/-!
# Exact split-square realization for the packed Möbius sieve

The optimized production kernel separates each suffix-prime update into:

1. one product/count update for every row divisible by `p`; and
2. one idempotent square mark for every row divisible by `p²`.

This removes a 64-bit `n % p²` operation from every divisor event.  Early
square streams use one CUDA block whose threads visit event ordinals

```
iteration * 256 + thread,
```

while later streams use one thread per prime and enumerate the same ordinals
serially.  This file proves the architecture-independent facts needed by both
schedules:

* the block/thread coordinates enumerate every `p²` multiple exactly once;
* the serial event progression enumerates the same set; and
* moving all square marks after all product/count updates preserves the exact
  mathematical support state.

The remaining boundary is identifying the compiled CUDA launches, same-stream
ordering, and atomic operations with these definitions.
-/

set_option autoImplicit false

namespace SparkInterval.TernaryGoldbach.MobiusSplitSquareRealization

open SparkInterval.TernaryGoldbach.MobiusDenseSchedule
open SparkInterval.TernaryGoldbach.MobiusFusedFinalization
open SparkInterval.TernaryGoldbach.MobiusFusedSupport
open SparkInterval.TernaryGoldbach.MobiusResidue235
open SparkInterval.TernaryGoldbach.MobiusSegmentEventEnumeration

/-- One coordinate in the one-block-per-prime square-strike kernel. -/
structure SquareVisit where
  thread : Nat
  iteration : Nat
deriving DecidableEq, Repr

/-- Square-multiple event ordinal generated by a dense square coordinate. -/
def SquareVisit.event (visit : SquareVisit) : Nat :=
  visit.iteration * threadsPerBlock + visit.thread

/-- A legal dense square coordinate visiting one segment row. -/
def SquareVisits
    (lower count prime offset : Nat) (visit : SquareVisit) : Prop :=
  visit.thread < threadsPerBlock ∧
    visit.event <
      multipleEventCount count
        (firstOffset lower (prime * prime)) (prime * prime) ∧
    multipleOffset
      (firstOffset lower (prime * prime)) (prime * prime)
      visit.event = offset

/-- Canonical thread and loop iteration owning one square event. -/
def squareOwnerVisit (event : Nat) : SquareVisit where
  thread := threadOwner event
  iteration := iterationOwner event

@[simp] theorem squareOwnerVisit_event (event : Nat) :
    (squareOwnerVisit event).event = event := by
  exact localEvent_decode event

theorem squareVisit_eq_owner
    {lower count prime offset event : Nat}
    (primePositive : 0 < prime)
    (eventOffset :
      multipleOffset
        (firstOffset lower (prime * prime)) (prime * prime)
        event = offset)
    {visit : SquareVisit}
    (visitValid : SquareVisits lower count prime offset visit) :
    visit = squareOwnerVisit event := by
  have squarePositive : 0 < prime * prime :=
    Nat.mul_pos primePositive primePositive
  have eventEq : visit.event = event :=
    multipleOffset_injective squarePositive
      (visitValid.2.2.trans eventOffset.symm)
  have threadEq :
      visit.thread = threadOwner event := by
    have modEq :=
      congrArg (fun value => value % threadsPerBlock) eventEq
    simpa [SquareVisit.event, threadOwner,
      Nat.mod_eq_of_lt visitValid.1] using modEq
  have iterationEq :
      visit.iteration = iterationOwner event := by
    have expanded :
        visit.iteration * threadsPerBlock + visit.thread =
          iterationOwner event * threadsPerBlock +
            threadOwner event := by
      calc
        visit.iteration * threadsPerBlock + visit.thread =
            visit.event := rfl
        _ = event := eventEq
        _ = iterationOwner event * threadsPerBlock +
              threadOwner event :=
          (localEvent_decode event).symm
    rw [threadEq] at expanded
    norm_num [threadsPerBlock] at expanded ⊢
    omega
  cases visit
  simp_all [squareOwnerVisit]

/-- Every in-segment row is divisible by `p²` iff exactly one dense
block/thread coordinate strikes it.  The same unique event ordinal is what
the later one-thread-per-prime loop enumerates directly. -/
theorem prime_sq_dvd_iff_existsUnique_squareVisit
    {lower count prime offset : Nat}
    (primePositive : 0 < prime)
    (offsetInSegment : offset < count) :
    prime * prime ∣ lower + offset ↔
      ∃! visit, SquareVisits lower count prime offset visit := by
  have squarePositive : 0 < prime * prime :=
    Nat.mul_pos primePositive primePositive
  constructor
  · intro divides
    have eventUnique :=
      (dvd_iff_existsUnique_event squarePositive offsetInSegment).mp
        divides
    rcases eventUnique with ⟨event, eventFacts, _unique⟩
    refine ⟨squareOwnerVisit event, ?_, ?_⟩
    · exact ⟨threadOwner_lt event, by
        simpa using eventFacts.1, by
        simpa using eventFacts.2⟩
    · intro visit visitValid
      exact squareVisit_eq_owner
        primePositive eventFacts.2 visitValid
  · rintro ⟨visit, visitValid, _unique⟩
    rw [← visitValid.2.2]
    exact dvd_multipleOffset lower
      (firstOffset lower (prime * prime)) (prime * prime)
      visit.event
      (firstOffset_dvd lower squarePositive)

/-! ## Reordering product/count and square events -/

/-- One suffix-prime event and the mathematical result of testing `p² ∣ n`. -/
structure SplitEvent where
  prime : Nat
  dividesSquare : Bool
deriving DecidableEq, Repr

/-- Product/count transition selected by one authenticated divisor event. -/
def applyDistinctEvent (support : Support) (event : SplitEvent) : Support :=
  updateProductCount support event.prime

/-- Square-bit transition selected by the corresponding square test. -/
def applySquareEvent (support : Support) (event : SplitEvent) : Support :=
  markSquareful support event.dividesSquare

/-- Reference inline execution: every divisor event updates all fields. -/
def inlineRun (support : Support) : List SplitEvent → Support
  | [] => support
  | event :: events =>
      inlineRun
        (update support event.prime event.dividesSquare) events

/-- First production phase: update only product and distinct-factor count. -/
def distinctRun (support : Support) : List SplitEvent → Support
  | [] => support
  | event :: events =>
      distinctRun (applyDistinctEvent support event) events

/-- Second production phase: install only the idempotent square flags. -/
def squareRun (support : Support) : List SplitEvent → Support
  | [] => support
  | event :: events =>
      squareRun (applySquareEvent support event) events

/-- Production split execution over an identical authenticated event roster. -/
def splitRun (support : Support) (events : List SplitEvent) : Support :=
  squareRun (distinctRun support events) events

/-- Concurrent product/count CAS events have one schedule-independent
mathematical result. -/
theorem applyDistinctEvent_right_comm :
    RightCommutative applyDistinctEvent := by
  constructor
  intro support first second
  cases support
  simp [applyDistinctEvent, updateProductCount,
    Nat.mul_comm, Nat.mul_left_comm, Nat.add_comm, Nat.add_left_comm]

/-- Concurrent square OR events also have one schedule-independent result. -/
theorem applySquareEvent_right_comm :
    RightCommutative applySquareEvent := by
  constructor
  intro support first second
  exact markSquareful_markSquareful_comm
    support first.dividesSquare second.dividesSquare

theorem distinctRun_eq_foldl
    (support : Support) (events : List SplitEvent) :
    distinctRun support events =
      events.foldl applyDistinctEvent support := by
  induction events generalizing support with
  | nil =>
      rfl
  | cons event events inductionHypothesis =>
      simp only [distinctRun, List.foldl_cons]
      exact inductionHypothesis _

theorem squareRun_eq_foldl
    (support : Support) (events : List SplitEvent) :
    squareRun support events =
      events.foldl applySquareEvent support := by
  induction events generalizing support with
  | nil =>
      rfl
  | cons event events inductionHypothesis =>
      simp only [squareRun, List.foldl_cons]
      exact inductionHypothesis _

/-- Reordering concurrently serialized divisor events cannot change the
product/count phase. -/
theorem distinctRun_perm
    (support : Support) {first second : List SplitEvent}
    (permutation : first.Perm second) :
    distinctRun support first = distinctRun support second := by
  rw [distinctRun_eq_foldl, distinctRun_eq_foldl]
  letI : RightCommutative applyDistinctEvent :=
    applyDistinctEvent_right_comm
  exact permutation.foldl_eq support

/-- Reordering atomic square strikes cannot change the square phase. -/
theorem squareRun_perm
    (support : Support) {first second : List SplitEvent}
    (permutation : first.Perm second) :
    squareRun support first = squareRun support second := by
  rw [squareRun_eq_foldl, squareRun_eq_foldl]
  letI : RightCommutative applySquareEvent :=
    applySquareEvent_right_comm
  exact permutation.foldl_eq support

/-- The complete two-phase result is invariant under any common permutation
of the authenticated prime-event roster. -/
theorem splitRun_perm
    (support : Support) {first second : List SplitEvent}
    (permutation : first.Perm second) :
    splitRun support first = splitRun support second := by
  rw [splitRun, splitRun]
  rw [distinctRun_perm support permutation]
  exact squareRun_perm _ permutation

/-- One square mark commutes through the entire product/count pass. -/
theorem markSquareful_distinctRun
    (support : Support) (events : List SplitEvent)
    (dividesSquare : Bool) :
    markSquareful (distinctRun support events) dividesSquare =
      distinctRun (markSquareful support dividesSquare) events := by
  induction events generalizing support with
  | nil =>
      rfl
  | cons event events inductionHypothesis =>
      simp only [distinctRun, applyDistinctEvent]
      rw [inductionHypothesis]
      rw [markSquareful_updateProductCount_comm]

/-- Moving every square test to the later `p²` pass is exactly equivalent to
the reference inline update sequence. -/
theorem splitRun_eq_inlineRun
    (support : Support) (events : List SplitEvent) :
    splitRun support events = inlineRun support events := by
  induction events generalizing support with
  | nil =>
      rfl
  | cons event events inductionHypothesis =>
      rw [splitRun]
      simp only [distinctRun, squareRun,
        applyDistinctEvent, applySquareEvent]
      rw [markSquareful_distinctRun]
      rw [← splitRun]
      rw [← update_eq_markSquareful_updateProductCount]
      rw [inductionHypothesis]
      rfl

/-! ## Connection to the source Möbius fold -/

/-- Exact event roster for one row: only actual prime divisors enter the CAS
pass, and the corresponding Boolean records the `p²` strike predicate. -/
def rowSplitEvents (number : Nat) (primes : List Nat) : List SplitEvent :=
  (primes.filter fun prime => prime ∣ number).map fun prime =>
    {
      prime
      dividesSquare := decide (prime * prime ∣ number)
    }

theorem rowSplitEvents_cons
    (number prime : Nat) (primes : List Nat) :
    rowSplitEvents number (prime :: primes) =
      if prime ∣ number then
        {
          prime
          dividesSquare := decide (prime * prime ∣ number)
        } :: rowSplitEvents number primes
      else
        rowSplitEvents number primes := by
  by_cases divides : prime ∣ number <;>
    simp [rowSplitEvents, divides]

/-- The inline event roster is definitionally the conditional source prime
fold after filtering away primes which do not divide this row. -/
theorem inlineRun_rowSplitEvents
    (number : Nat) (primes : List Nat) (support : Support) :
    inlineRun support (rowSplitEvents number primes) =
      primes.foldl (applyPrime number) support := by
  induction primes generalizing support with
  | nil =>
      rfl
  | cons prime primes inductionHypothesis =>
      by_cases divides : prime ∣ number
      · rw [rowSplitEvents_cons, if_pos divides,
          List.foldl_cons]
        simp only [inlineRun]
        rw [applyPrime, if_pos divides]
        exact inductionHypothesis _
      · rw [rowSplitEvents_cons, if_neg divides,
          List.foldl_cons]
        rw [applyPrime, if_neg divides]
        exact inductionHypothesis _

/-- The optimized two-pass suffix is the exact residue-seeded source fold. -/
theorem splitRun_residueSeeded_eq_suffixFold
    (number : Nat) (suffix : List Nat) :
    splitRun (residueSeed number) (rowSplitEvents number suffix) =
      suffix.foldl (applyPrime number) (residueSeed number) := by
  rw [splitRun_eq_inlineRun]
  exact inlineRun_rowSplitEvents number suffix (residueSeed number)

/-- End-to-end abstract correctness of the optimized split-square algorithm,
under the same explicit source-row support invariant as the reference fold. -/
theorem finalize_splitRun_residueSeeded_eq_moebius
    (number : Nat) (suffix : List Nat)
    (valid :
      SourceRowSupportValid number
        (foldSupport number (seedPrimes ++ suffix))) :
    finalize number
        (splitRun (residueSeed number)
          (rowSplitEvents number suffix)) =
      ArithmeticFunction.moebius number := by
  rw [splitRun_residueSeeded_eq_suffixFold]
  exact finalize_residueSeeded_eq_moebius number suffix valid

#print axioms squareOwnerVisit_event
#print axioms squareVisit_eq_owner
#print axioms prime_sq_dvd_iff_existsUnique_squareVisit
#print axioms applyDistinctEvent_right_comm
#print axioms applySquareEvent_right_comm
#print axioms distinctRun_perm
#print axioms squareRun_perm
#print axioms splitRun_perm
#print axioms markSquareful_distinctRun
#print axioms splitRun_eq_inlineRun
#print axioms inlineRun_rowSplitEvents
#print axioms splitRun_residueSeeded_eq_suffixFold
#print axioms finalize_splitRun_residueSeeded_eq_moebius

end SparkInterval.TernaryGoldbach.MobiusSplitSquareRealization
