/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.TernaryGoldbach.MobiusPrimeRosterCertificateBridge

/-!
# A linear-work segmented-sieve certificate for the production prime roster

The generic V2 roster checker is an appropriate certificate for a short list
of base primes, but a poor production format for every prime through `10^8`:
it gives every listed prime a Lucas/Pratt row and every omitted integer an
explicit factor pair.

This file supplies a smaller deterministic-sieve boundary.  A certificate has
one `factorCode` for every integer `n` from `2` through `bound`:

* code `0` says that `n` survived the sieve;
* a nonzero code is an actual base-prime divisor of `n`.

Acceptance checks both directions which matter:

* every nonzero code really is a proper divisor from the checked base roster;
* every multiple `p * q`, for `p` in the base roster and `q ≥ p`, has a
  nonzero code.

The second check strides through multiples.  It does not trial-divide every
candidate by every base prime.  When the base roster is complete through
`baseBound` and `bound ≤ baseBound²`, the two checks prove that code zero is
equivalent to primality throughout the requested interval.

`Array Nat` is the architecture-neutral source representation.  A production
artifact can encode each factor code as a little-endian `uint16`, because the
largest required code is at most `10^4`; a C/LLVM refinement of that packed
reader is deliberately a separate compiler obligation.  The mathematical
checker and all theorems in this file are ordinary Lean definitions and use
no native decision procedure.
-/

set_option autoImplicit false

namespace SparkInterval.TernaryGoldbach.MobiusSegmentedSieveRoster

open SparkInterval.TernaryGoldbach.MobiusPrimeRosterCompleteness
open SparkInterval.TernaryGoldbach.MobiusPrimeRosterCertificateBridge
open SparkInterval.TernaryGoldbach.Sqrt218Operational.V2

/-! ## Allocation-free bounded scans -/

/-- Check `cell` at `start, ..., start + count - 1`.

The recursive call is in tail position.  Unlike a `List.range` formulation,
compiled execution does not first allocate a list proportional to `count`. -/
def scanRange (start : Nat) : Nat → (Nat → Bool) → Bool
  | 0, _cell => true
  | count + 1, cell =>
      if cell start then
        scanRange (start + 1) count cell
      else
        false

/-- Logical elimination rule for the allocation-free bounded scan. -/
theorem scanRange_sound
    {start count : Nat} {cell : Nat → Bool}
    (checked : scanRange start count cell = true) :
    ∀ index, start ≤ index → index < start + count →
      cell index = true := by
  induction count generalizing start with
  | zero =>
      intro index lower upper
      omega
  | succ count inductionHypothesis =>
      simp only [scanRange] at checked
      split at checked
      next currentTrue =>
        intro index lower upper
        by_cases current : index = start
        · simpa [current] using currentTrue
        · apply inductionHypothesis checked index
          · omega
          · omega
      next =>
        contradiction

/-! ## Factor-code certificate and executable checks -/

/-- Code for `number`; out-of-range reads are zero.

Exact array length is checked by `shapeCheck`, so the default cannot occur in
an accepted production artifact. -/
def factorCodeAt (factorCodes : Array Nat) (number : Nat) : Nat :=
  factorCodes.getD (number - 2) 0

/-- A nonzero code must name an actual proper base-prime divisor. -/
def witnessCell
    (basePrimes : List Nat) (factorCodes : Array Nat)
    (number : Nat) : Bool :=
  let factor := factorCodeAt factorCodes number
  if factor = 0 then
    true
  else
    decide (
      factor ∈ basePrimes ∧
      factor < number ∧
      factor ∣ number)

/-- Check one factor code for every integer from `2` through `bound`. -/
def witnessCheck
    (bound : Nat) (basePrimes : List Nat)
    (factorCodes : Array Nat) : Bool :=
  scanRange 0 (bound - 1) fun offset =>
    witnessCell basePrimes factorCodes (offset + 2)

/-- Every sieve strike generated by one base prime must be marked.

The quotient range is
`prime ≤ quotient ≤ bound / prime`; hence the checked numbers are precisely
`prime * quotient` from `prime²` through the bound. -/
def primeCoverageCheck
    (bound : Nat) (factorCodes : Array Nat)
    (prime : Nat) : Bool :=
  scanRange prime (bound / prime + 1 - prime) fun quotient =>
    decide (factorCodeAt factorCodes (prime * quotient) ≠ 0)

/-- Check all strike progressions from the supplied base-prime roster. -/
def coverageCheck
    (bound : Nat) (basePrimes : List Nat)
    (factorCodes : Array Nat) : Bool :=
  basePrimes.all fun prime =>
    primeCoverageCheck bound factorCodes prime

/-- Structural guard for the exact interval and square-root base regime. -/
def shapeCheck
    (baseBound bound : Nat) (factorCodes : Array Nat) : Bool :=
  decide (
    2 ≤ bound ∧
    bound ≤ baseBound * baseBound ∧
    factorCodes.size = bound - 1)

/-- Source-level segmented-sieve checker.

For production this performs one pass over the factor-code table, plus
strided reads along the base-prime progressions. -/
def sieveRosterCheck
    (baseBound bound : Nat) (basePrimes : List Nat)
    (factorCodes : Array Nat) : Bool :=
  shapeCheck baseBound bound factorCodes &&
    (witnessCheck bound basePrimes factorCodes &&
      coverageCheck bound basePrimes factorCodes)

/-! ## Canonical roster and byte binding -/

/-- The exact finite set of sieve survivors. -/
def rosterFinset (bound : Nat) (factorCodes : Array Nat) : Finset Nat :=
  (Finset.Icc 2 bound).filter fun number =>
    factorCodeAt factorCodes number = 0

/-- Ascending canonical list of sieve survivors.

This uses the executable increasing range directly, rather than sorting a
`Finset`; small checked rosters can therefore be reduced by ordinary kernel
`decide` and production execution has an obvious streaming implementation. -/
def rosterList (bound : Nat) (factorCodes : Array Nat) : List Nat :=
  (List.range' 2 (bound - 1)).filter fun number =>
    decide (factorCodeAt factorCodes number = 0)

/-- Bind an independently decoded list to the exact sieve survivors. -/
def rosterBindingCheck
    (bound : Nat) (factorCodes : Array Nat)
    (rawPrimes : List Nat) : Bool :=
  decide (rawPrimes = rosterList bound factorCodes)

/-- Canonical four-byte little-endian encoding of one natural. -/
def encodeU32LE (value : Nat) : List UInt8 :=
  (List.range 4).map fun index =>
    UInt8.ofNat ((value / 256 ^ index) % 256)

@[simp] theorem encodeU32LE_length (value : Nat) :
    (encodeU32LE value).length = 4 := by
  simp [encodeU32LE]

/-- Canonical `u32le` byte stream for an ascending roster. -/
def encodeRosterU32LE (primes : List Nat) : ByteArray :=
  (primes.flatMap encodeU32LE).toByteArray

@[simp] theorem encodeRosterU32LE_size (primes : List Nat) :
    (encodeRosterU32LE primes).size = 4 * primes.length := by
  simp [encodeRosterU32LE, List.length_flatMap, Nat.mul_comm]

/-- Bind raw CUDA input bytes to an already checked mathematical roster. -/
def rosterBytesBindingCheck
    (rawBytes : ByteArray) (primes : List Nat) : Bool :=
  decide (rawBytes = encodeRosterU32LE primes)

/-- Canonical two-byte little-endian encoding of one factor code. -/
def encodeU16LE (value : Nat) : List UInt8 :=
  (List.range 2).map fun index =>
    UInt8.ofNat ((value / 256 ^ index) % 256)

@[simp] theorem encodeU16LE_length (value : Nat) :
    (encodeU16LE value).length = 2 := by
  simp [encodeU16LE]

/-- Packed representation intended for the production factor-code artifact. -/
def encodeFactorCodesU16LE (factorCodes : Array Nat) : ByteArray :=
  (factorCodes.toList.flatMap encodeU16LE).toByteArray

@[simp] theorem encodeFactorCodesU16LE_size
    (factorCodes : Array Nat) :
    (encodeFactorCodesU16LE factorCodes).size =
      2 * factorCodes.size := by
  simp [encodeFactorCodesU16LE, List.length_flatMap, Nat.mul_comm]

/-- Bind packed factor-code bytes to the architecture-neutral source array. -/
def factorCodeBytesBindingCheck
    (rawBytes : ByteArray) (factorCodes : Array Nat) : Bool :=
  decide (rawBytes = encodeFactorCodesU16LE factorCodes)

theorem rosterBindingCheck_sound
    {bound : Nat} {factorCodes : Array Nat}
    {rawPrimes : List Nat}
    (checked :
      rosterBindingCheck bound factorCodes rawPrimes = true) :
    rawPrimes = rosterList bound factorCodes := by
  simpa [rosterBindingCheck] using checked

theorem rosterBytesBindingCheck_sound
    {rawBytes : ByteArray} {primes : List Nat}
    (checked : rosterBytesBindingCheck rawBytes primes = true) :
    rawBytes = encodeRosterU32LE primes := by
  simpa only [rosterBytesBindingCheck, decide_eq_true_eq] using checked

theorem factorCodeBytesBindingCheck_sound
    {rawBytes : ByteArray} {factorCodes : Array Nat}
    (checked :
      factorCodeBytesBindingCheck rawBytes factorCodes = true) :
    rawBytes = encodeFactorCodesU16LE factorCodes := by
  simpa only [factorCodeBytesBindingCheck,
    decide_eq_true_eq] using checked

/-! ## Soundness of the two sieve directions -/

theorem witnessCheck_sound
    {bound : Nat} {basePrimes : List Nat}
    {factorCodes : Array Nat}
    (checked : witnessCheck bound basePrimes factorCodes = true)
    {number : Nat}
    (numberLower : 2 ≤ number)
    (numberUpper : number ≤ bound)
    (marked : factorCodeAt factorCodes number ≠ 0) :
    factorCodeAt factorCodes number ∈ basePrimes ∧
      factorCodeAt factorCodes number < number ∧
      factorCodeAt factorCodes number ∣ number := by
  have offsetLower : 0 ≤ number - 2 := Nat.zero_le _
  have offsetUpper : number - 2 < 0 + (bound - 1) := by
    omega
  have cellChecked :=
    scanRange_sound checked (number - 2)
      offsetLower offsetUpper
  have offsetNumber : number - 2 + 2 = number := by
    omega
  rw [offsetNumber] at cellChecked
  simp only [witnessCell, marked, if_false,
    decide_eq_true_eq] at cellChecked
  exact cellChecked

theorem coverageCheck_sound
    {bound : Nat} {basePrimes : List Nat}
    {factorCodes : Array Nat}
    (checked : coverageCheck bound basePrimes factorCodes = true)
    {prime number : Nat}
    (primeMember : prime ∈ basePrimes)
    (primePositive : 0 < prime)
    (primeSquareLe : prime * prime ≤ number)
    (numberUpper : number ≤ bound)
    (primeDivides : prime ∣ number) :
    factorCodeAt factorCodes number ≠ 0 := by
  rw [coverageCheck, List.all_eq_true] at checked
  have primeChecked := checked prime primeMember
  have reconstruct : prime * (number / prime) = number :=
    Nat.mul_div_cancel' primeDivides
  have quotientLower : prime ≤ number / prime := by
    rw [Nat.le_div_iff_mul_le primePositive]
    exact primeSquareLe
  have quotientUpper : number / prime ≤ bound / prime :=
    Nat.div_le_div_right numberUpper
  have primeLeBoundDiv : prime ≤ bound / prime :=
    quotientLower.trans quotientUpper
  have quotientRange :
      number / prime <
        prime + (bound / prime + 1 - prime) := by
    omega
  have cellChecked :=
    scanRange_sound primeChecked (number / prime)
      quotientLower quotientRange
  rw [reconstruct] at cellChecked
  exact of_decide_eq_true cellChecked

/-! ## Exact-prime theorem -/

/-- Acceptance of the deterministic sieve implies that its survivors are
exactly all primes through `bound`. -/
theorem sieveRosterCheck_sound
    {baseBound bound : Nat} {basePrimes : List Nat}
    {factorCodes : Array Nat}
    (baseValid : PrimeRosterThrough baseBound basePrimes)
    (checked :
      sieveRosterCheck baseBound bound basePrimes factorCodes = true) :
    PrimeRosterThrough bound (rosterList bound factorCodes) := by
  simp only [sieveRosterCheck, Bool.and_eq_true,
    shapeCheck, decide_eq_true_eq] at checked
  have boundLower : 2 ≤ bound := checked.1.1
  have boundSquare : bound ≤ baseBound * baseBound :=
    checked.1.2.1
  have witnessesChecked := checked.2.1
  have coverageChecked := checked.2.2
  refine {
    nodup :=
      (List.nodup_range' :
        (List.range' 2 (bound - 1)).Nodup).filter _
    entriesPrime := ?_
    complete := ?_
  }
  · intro number member
    have survivorFiltered :=
      List.mem_filter.mp member
    have survivorBounds : 2 ≤ number ∧ number ≤ bound := by
      rw [List.mem_range'_1] at survivorFiltered
      omega
    have survivorZero :
        factorCodeAt factorCodes number = 0 :=
      of_decide_eq_true survivorFiltered.2
    have numberLower : 2 ≤ number := survivorBounds.1
    have numberUpper : number ≤ bound := survivorBounds.2
    by_contra numberNotPrime
    let prime := number.minFac
    have numberNeOne : number ≠ 1 := by omega
    have primePrime : Nat.Prime prime :=
      Nat.minFac_prime numberNeOne
    have primeDivides : prime ∣ number :=
      Nat.minFac_dvd number
    have primeSquareLeNumber : prime * prime ≤ number := by
      simpa [pow_two] using
        Nat.minFac_sq_le_self (by omega) numberNotPrime
    have primeLeBaseBound : prime ≤ baseBound :=
      nonneg_le_nonneg_of_sq_le_sq
        (Nat.zero_le baseBound)
        (primeSquareLeNumber.trans
          (numberUpper.trans boundSquare))
    have primeMember : prime ∈ basePrimes :=
      baseValid.complete prime primePrime primeLeBaseBound
    have marked :=
      coverageCheck_sound coverageChecked
        primeMember primePrime.pos primeSquareLeNumber
        numberUpper primeDivides
    exact marked survivorZero
  · intro prime primePrime primeUpper
    have primeLower : 2 ≤ prime := primePrime.two_le
    have survivor :
        factorCodeAt factorCodes prime = 0 := by
      by_contra marked
      obtain ⟨factorMember, factorLt, factorDivides⟩ :=
        witnessCheck_sound witnessesChecked
          primeLower primeUpper marked
      have factorPrime :=
        baseValid.entriesPrime
          (factorCodeAt factorCodes prime) factorMember
      rcases (Nat.dvd_prime primePrime).mp factorDivides with
        factorOne | factorSelf
      · exact factorPrime.ne_one factorOne
      · omega
    rw [rosterList, List.mem_filter, List.mem_range'_1]
    exact ⟨by omega, decide_eq_true survivor⟩

/-- Acceptance plus list binding yields the exact contract for the list
consumed by the native Möbius runner. -/
theorem boundRosterCheck_sound
    {baseBound bound : Nat} {basePrimes rawPrimes : List Nat}
    {factorCodes : Array Nat}
    (baseValid : PrimeRosterThrough baseBound basePrimes)
    (sieveChecked :
      sieveRosterCheck baseBound bound basePrimes factorCodes = true)
    (bindingChecked :
      rosterBindingCheck bound factorCodes rawPrimes = true) :
    PrimeRosterThrough bound rawPrimes := by
  rw [rosterBindingCheck_sound bindingChecked]
  exact sieveRosterCheck_sound baseValid sieveChecked

/-! ## Reuse of the small V2 base-prime certificate -/

/-- A checked V2 certificate only through `baseBound`, followed by the linear
sieve certificate, proves the full roster. -/
theorem boundRosterCheck_of_v2Base
    {baseBound bound : Nat}
    {baseCertificate : PrimeRosterCertificate}
    {factorCodes : Array Nat} {rawPrimes : List Nat}
    (baseChecked :
      primeRosterCheck baseBound baseCertificate = true)
    (sieveChecked :
      sieveRosterCheck baseBound bound
        (MobiusPrimeRosterCertificateBridge.rosterList baseCertificate)
        factorCodes = true)
    (bindingChecked :
      rosterBindingCheck bound factorCodes rawPrimes = true) :
    PrimeRosterThrough bound rawPrimes := by
  apply boundRosterCheck_sound
    (primeRosterThrough_of_checkedCertificate baseChecked)
    sieveChecked bindingChecked

/-! ## One Boolean boundary for trusted execution -/

/-- One fail-closed Boolean after the base-prime roster has been established.

This form permits a recursively checked sieve roster to supply the base,
avoiding a large V2/Pratt certificate even at the `10^4` intermediate bound. -/
def certifiedRosterCheckWithBase
    (baseBound bound : Nat) (basePrimes : List Nat)
    (factorCodes : Array Nat)
    (rawFactorCodeBytes rawRosterBytes : ByteArray)
    (rawPrimes : List Nat) : Bool :=
  sieveRosterCheck baseBound bound basePrimes factorCodes &&
    (rosterBindingCheck bound factorCodes rawPrimes &&
      (factorCodeBytesBindingCheck rawFactorCodeBytes factorCodes &&
        rosterBytesBindingCheck rawRosterBytes rawPrimes))

/-- Soundness of the single Boolean boundary with an already proved base
roster. -/
theorem certifiedRosterCheckWithBase_sound
    {baseBound bound : Nat} {basePrimes : List Nat}
    {factorCodes : Array Nat}
    {rawFactorCodeBytes rawRosterBytes : ByteArray}
    {rawPrimes : List Nat}
    (baseValid : PrimeRosterThrough baseBound basePrimes)
    (checked :
      certifiedRosterCheckWithBase baseBound bound basePrimes
        factorCodes rawFactorCodeBytes rawRosterBytes rawPrimes = true) :
    PrimeRosterThrough bound rawPrimes ∧
      rawFactorCodeBytes =
        encodeFactorCodesU16LE factorCodes ∧
      rawRosterBytes = encodeRosterU32LE rawPrimes := by
  simp only [certifiedRosterCheckWithBase,
    Bool.and_eq_true] at checked
  refine ⟨
    boundRosterCheck_sound baseValid
      checked.1 checked.2.1,
    factorCodeBytesBindingCheck_sound checked.2.2.1,
    rosterBytesBindingCheck_sound checked.2.2.2⟩

/-- One fail-closed Boolean check for:

* the short V2 base-prime certificate;
* the linear-work sieve certificate;
* equality with the decoded roster supplied to the Möbius runner; and
* canonical byte encodings of both production inputs.

The trusted-compute receipt can attest execution of this one source-level
predicate. -/
def certifiedRosterCheck
    (baseBound bound : Nat)
    (baseCertificate : PrimeRosterCertificate)
    (factorCodes : Array Nat)
    (rawFactorCodeBytes rawRosterBytes : ByteArray)
    (rawPrimes : List Nat) : Bool :=
  primeRosterCheck baseBound baseCertificate &&
    certifiedRosterCheckWithBase baseBound bound
      (MobiusPrimeRosterCertificateBridge.rosterList baseCertificate)
      factorCodes rawFactorCodeBytes rawRosterBytes rawPrimes

/-- Acceptance of the single trusted-execution predicate proves the exact
prime roster and both byte bindings. -/
theorem certifiedRosterCheck_sound
    {baseBound bound : Nat}
    {baseCertificate : PrimeRosterCertificate}
    {factorCodes : Array Nat}
    {rawFactorCodeBytes rawRosterBytes : ByteArray}
    {rawPrimes : List Nat}
    (checked :
      certifiedRosterCheck baseBound bound baseCertificate
        factorCodes rawFactorCodeBytes rawRosterBytes rawPrimes = true) :
    PrimeRosterThrough bound rawPrimes ∧
      rawFactorCodeBytes =
        encodeFactorCodesU16LE factorCodes ∧
      rawRosterBytes = encodeRosterU32LE rawPrimes := by
  simp only [certifiedRosterCheck, Bool.and_eq_true] at checked
  exact certifiedRosterCheckWithBase_sound
    (primeRosterThrough_of_checkedCertificate checked.1)
    checked.2

/-- The production path needs V2 evidence only through `10^4`; the linear
factor-code sieve then covers the canonical roster through `10^8`. -/
theorem productionPrimeRosterThrough_of_segmentedSieve
    {baseCertificate : PrimeRosterCertificate}
    {factorCodes : Array Nat} {rawPrimes : List Nat}
    (baseChecked :
      primeRosterCheck 10_000 baseCertificate = true)
    (sieveChecked :
      sieveRosterCheck 10_000 productionPrimeBound
        (MobiusPrimeRosterCertificateBridge.rosterList baseCertificate)
        factorCodes = true)
    (bindingChecked :
      rosterBindingCheck productionPrimeBound
        factorCodes rawPrimes = true) :
    PrimeRosterThrough productionPrimeBound rawPrimes := by
  apply boundRosterCheck_of_v2Base
    baseChecked sieveChecked bindingChecked

/-- Production specialization of the single accepted Boolean predicate. -/
theorem productionCertifiedRosterCheck_sound
    {baseCertificate : PrimeRosterCertificate}
    {factorCodes : Array Nat}
    {rawFactorCodeBytes rawRosterBytes : ByteArray}
    {rawPrimes : List Nat}
    (checked :
      certifiedRosterCheck 10_000 productionPrimeBound
        baseCertificate factorCodes rawFactorCodeBytes
        rawRosterBytes rawPrimes = true) :
    PrimeRosterThrough productionPrimeBound rawPrimes ∧
      rawFactorCodeBytes =
        encodeFactorCodesU16LE factorCodes ∧
      rawRosterBytes = encodeRosterU32LE rawPrimes :=
  certifiedRosterCheck_sound checked

/-- No accepted production factor code can be truncated by the canonical
`uint16` encoder.  A nonzero code is a member of the V2 base roster, and that
check proves every base entry is at most `10^4`. -/
theorem productionCertifiedRosterCheck_factorCode_lt_u16
    {baseCertificate : PrimeRosterCertificate}
    {factorCodes : Array Nat}
    {rawFactorCodeBytes rawRosterBytes : ByteArray}
    {rawPrimes : List Nat}
    (checked :
      certifiedRosterCheck 10_000 productionPrimeBound
        baseCertificate factorCodes rawFactorCodeBytes
        rawRosterBytes rawPrimes = true)
    {number : Nat}
    (numberLower : 2 ≤ number)
    (numberUpper : number ≤ productionPrimeBound) :
    factorCodeAt factorCodes number < 2 ^ 16 := by
  have checks := checked
  simp only [certifiedRosterCheck, Bool.and_eq_true] at checks
  have baseFacts := primeRosterCheck_sound checks.1
  have combinedChecked := checks.2
  simp only [certifiedRosterCheckWithBase,
    Bool.and_eq_true] at combinedChecked
  have sieveChecked := combinedChecked.1
  simp only [sieveRosterCheck, Bool.and_eq_true,
    shapeCheck, decide_eq_true_eq] at sieveChecked
  by_cases zero : factorCodeAt factorCodes number = 0
  · simp [zero]
  · have witness :=
      witnessCheck_sound sieveChecked.2.1
        numberLower numberUpper zero
    obtain ⟨index, equalValue⟩ :=
      List.mem_ofFn.mp witness.1
    have codeLe :
        factorCodeAt factorCodes number ≤ 10_000 := by
      rw [← equalValue]
      exact baseFacts.value_le index index.isLt
    omega

/-- The accepted production factor-code artifact has exactly
`2 * (10^8 - 1) = 199,999,998` bytes. -/
theorem productionFactorCodeBytes_size
    {baseCertificate : PrimeRosterCertificate}
    {factorCodes : Array Nat}
    {rawFactorCodeBytes rawRosterBytes : ByteArray}
    {rawPrimes : List Nat}
    (checked :
      certifiedRosterCheck 10_000 productionPrimeBound
        baseCertificate factorCodes rawFactorCodeBytes
        rawRosterBytes rawPrimes = true) :
    rawFactorCodeBytes.size = 199_999_998 := by
  have sound := productionCertifiedRosterCheck_sound checked
  have checks := checked
  simp only [certifiedRosterCheck, Bool.and_eq_true] at checks
  have combinedChecked := checks.2
  simp only [certifiedRosterCheckWithBase,
    Bool.and_eq_true] at combinedChecked
  have sieveChecked := combinedChecked.1
  simp only [sieveRosterCheck, Bool.and_eq_true,
    shapeCheck, decide_eq_true_eq] at sieveChecked
  rw [sound.2.1, encodeFactorCodesU16LE_size,
    sieveChecked.1.2.2]
  norm_num [productionPrimeBound]

#print axioms scanRange_sound
#print axioms witnessCheck_sound
#print axioms coverageCheck_sound
#print axioms rosterBytesBindingCheck_sound
#print axioms factorCodeBytesBindingCheck_sound
#print axioms sieveRosterCheck_sound
#print axioms boundRosterCheck_of_v2Base
#print axioms certifiedRosterCheckWithBase_sound
#print axioms certifiedRosterCheck_sound
#print axioms productionPrimeRosterThrough_of_segmentedSieve
#print axioms productionCertifiedRosterCheck_sound
#print axioms productionCertifiedRosterCheck_factorCode_lt_u16
#print axioms productionFactorCodeBytes_size

end SparkInterval.TernaryGoldbach.MobiusSegmentedSieveRoster
