/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.TernaryGoldbach.MobiusFusedSupport

/-!
# Exact schedule for the load-balanced dense-prime Möbius pass

The optimized CUDA sieve assigns a rectangular grid of block slots to the
first dense primes. Within one prime, every block owns one contiguous range
of multiple ordinals and every thread walks that range with block-sized
stride. This module proves the architecture-independent integer partition:
flat blocks decode uniquely, every event has exactly one owner, and the
declared launch cap is sufficient for every prime at least two.

The production residue-235 initializer removes the event passes for 2, 3,
and 5, so its suffix begins at 7.  This module also proves that 147 slots are
the exact safe minimum for that suffix at the unchanged public row cap.  The
native implementation deliberately retains the measured 512-slot schedule
because a sweep of 147 and nearby aligned choices found no material speedup.

It does not claim that CUDA executes these definitions; that remains a
machine-refinement boundary. Together with `MobiusFusedSupport.update_comm`,
the partition explains why changing the order of concurrent prime updates
does not change the mathematical support state.
-/

set_option autoImplicit false

namespace SparkInterval.TernaryGoldbach.MobiusDenseSchedule

/-- Threads in each dense-prime block. -/
def threadsPerBlock : ℕ := 256

/-- Maximum event-loop iterations owned by one thread. -/
def iterationsPerThread : ℕ := 4096

/-- Consecutive multiple ordinals covered by one block slot. -/
def eventsPerBlock : ℕ :=
  threadsPerBlock * iterationsPerThread

/-- Block slots reserved for each load-balanced dense prime. -/
def blockSlotsPerPrime : ℕ := 512

/-- Number of dense primes admitted to the load-balanced rectangular grid. -/
def multiblockPrimeCount : ℕ := 200

/-- Exact rectangular grid size used by the current CUDA launch. -/
def multiblockGrid : ℕ :=
  multiblockPrimeCount * blockSlotsPerPrime

/-- Maximum segment row count accepted by the load-balanced entry point. -/
def maximumSegmentRows : ℕ :=
  2 * blockSlotsPerPrime * eventsPerBlock

/-- First prime in the event suffix after the exact residue-235 seed. -/
def residueSuffixMinimumPrime : ℕ := 7

/-- Exact minimum block-slot capacity for a residue-seeded event suffix at
the unchanged public row cap. -/
def residueMinimumBlockSlotsPerPrime : ℕ := 147

/-- Dense-prime index encoded by a flat CUDA block index. -/
def primeIndex (flatBlock : ℕ) : ℕ :=
  flatBlock / blockSlotsPerPrime

/-- Per-prime block ordinal encoded by a flat CUDA block index. -/
def blockOrdinal (flatBlock : ℕ) : ℕ :=
  flatBlock % blockSlotsPerPrime

/-- First multiple ordinal owned by a block. -/
def eventBegin (block : ℕ) : ℕ :=
  block * eventsPerBlock

/-- Exclusive event stop, clipped to the number of multiples. -/
def eventStop (eventCount block : ℕ) : ℕ :=
  min (eventBegin block + eventsPerBlock) eventCount

/-- Unique block ordinal that owns an event. -/
def eventOwner (event : ℕ) : ℕ :=
  event / eventsPerBlock

/-- Event ordinal local to its owning block. -/
def eventLocal (event : ℕ) : ℕ :=
  event % eventsPerBlock

/-- CUDA thread that owns a block-local event. -/
def threadOwner (localEvent : ℕ) : ℕ :=
  localEvent % threadsPerBlock

/-- Iteration of that thread's strided loop. -/
def iterationOwner (localEvent : ℕ) : ℕ :=
  localEvent / threadsPerBlock

/-- Number of in-segment multiples from a supplied first offset. This is the
same integer formula used by the CUDA kernel. -/
def multipleEventCount (count firstOffset prime : ℕ) : ℕ :=
  if firstOffset ≥ count then 0
  else 1 + (count - 1 - firstOffset) / prime

/-- Row offset generated by one prime/event pair. -/
def multipleOffset (firstOffset prime event : ℕ) : ℕ :=
  firstOffset + event * prime

theorem eventsPerBlock_eq :
    eventsPerBlock = 1_048_576 := by
  norm_num [eventsPerBlock, threadsPerBlock, iterationsPerThread]

theorem maximumSegmentRows_eq :
    maximumSegmentRows = 1_073_741_824 := by
  norm_num [maximumSegmentRows, blockSlotsPerPrime, eventsPerBlock,
    threadsPerBlock, iterationsPerThread]

theorem multiblockGrid_eq :
    multiblockGrid = 102_400 := by
  norm_num [multiblockGrid, multiblockPrimeCount, blockSlotsPerPrime]

theorem residueMinimumBlockSlotsPerPrime_eq :
    residueMinimumBlockSlotsPerPrime = 147 := by
  rfl

/-- The exact worst-case `p=7` event count fits 147 slots. -/
theorem residueMinimumSlots_sufficient_at_public_cap :
    multipleEventCount maximumSegmentRows 0 residueSuffixMinimumPrime ≤
      residueMinimumBlockSlotsPerPrime * eventsPerBlock := by
  norm_num [multipleEventCount, maximumSegmentRows,
    residueSuffixMinimumPrime, residueMinimumBlockSlotsPerPrime,
    blockSlotsPerPrime, eventsPerBlock, threadsPerBlock,
    iterationsPerThread]

/-- One fewer slot fails at the exact public-cap, `p=7`, zero-offset case, so
147 is not merely sufficient but minimal. -/
theorem residuePreviousSlotCount_insufficient :
    (residueMinimumBlockSlotsPerPrime - 1) * eventsPerBlock <
      multipleEventCount maximumSegmentRows 0
        residueSuffixMinimumPrime := by
  norm_num [multipleEventCount, maximumSegmentRows,
    residueSuffixMinimumPrime, residueMinimumBlockSlotsPerPrime,
    blockSlotsPerPrime, eventsPerBlock, threadsPerBlock,
    iterationsPerThread]

theorem flatBlock_decode (flatBlock : ℕ) :
    primeIndex flatBlock * blockSlotsPerPrime +
      blockOrdinal flatBlock = flatBlock := by
  simpa [primeIndex, blockOrdinal, Nat.mul_comm] using
    Nat.div_add_mod flatBlock blockSlotsPerPrime

theorem primeIndex_lt
    {primeCount flatBlock : ℕ}
    (hflat : flatBlock < primeCount * blockSlotsPerPrime) :
    primeIndex flatBlock < primeCount := by
  rw [primeIndex, Nat.div_lt_iff_lt_mul]
  · exact hflat
  · norm_num [blockSlotsPerPrime]

theorem blockOrdinal_lt (flatBlock : ℕ) :
    blockOrdinal flatBlock < blockSlotsPerPrime := by
  exact Nat.mod_lt _ (by norm_num [blockSlotsPerPrime])

theorem eventBegin_owner_le (event : ℕ) :
    eventBegin (eventOwner event) ≤ event := by
  simpa [eventBegin, eventOwner] using
    Nat.div_mul_le_self event eventsPerBlock

theorem event_lt_owner_unclippedStop (event : ℕ) :
    event <
      eventBegin (eventOwner event) + eventsPerBlock := by
  have hremainder :
      event % eventsPerBlock < eventsPerBlock :=
    Nat.mod_lt _ (by norm_num [eventsPerBlock, threadsPerBlock,
      iterationsPerThread])
  have hdecomposition :
      eventBegin (eventOwner event) + event % eventsPerBlock =
        event := by
    simpa [eventBegin, eventOwner, Nat.mul_comm] using
      Nat.div_add_mod event eventsPerBlock
  omega

/-- Division by the block event width recovers the global event exactly. -/
theorem event_decode (event : ℕ) :
    eventBegin (eventOwner event) + eventLocal event = event := by
  simpa [eventBegin, eventOwner, eventLocal, Nat.mul_comm] using
    Nat.div_add_mod event eventsPerBlock

/-- Division by the CUDA block width recovers a block-local event exactly. -/
theorem localEvent_decode (localEvent : ℕ) :
    iterationOwner localEvent * threadsPerBlock +
      threadOwner localEvent = localEvent := by
  simpa [iterationOwner, threadOwner, Nat.mul_comm] using
    Nat.div_add_mod localEvent threadsPerBlock

theorem threadOwner_lt (localEvent : ℕ) :
    threadOwner localEvent < threadsPerBlock := by
  exact Nat.mod_lt _ (by norm_num [threadsPerBlock])

theorem iterationOwner_lt
    {localEvent : ℕ}
    (hlocal : localEvent < eventsPerBlock) :
    iterationOwner localEvent < iterationsPerThread := by
  rw [iterationOwner, Nat.div_lt_iff_lt_mul]
  · simpa [eventsPerBlock, Nat.mul_comm] using hlocal
  · norm_num [threadsPerBlock]

/-- The owning block, thread, and strided-loop iteration reconstruct every
global event ordinal exactly. -/
theorem event_block_thread_decode (event : ℕ) :
    eventBegin (eventOwner event) +
        (iterationOwner (eventLocal event) * threadsPerBlock +
          threadOwner (eventLocal event)) =
      event := by
  rw [localEvent_decode, event_decode]

/-- Every in-range event lies in its owner's clipped half-open interval. -/
theorem event_mem_owner
    {eventCount event : ℕ}
    (hevent : event < eventCount) :
    eventBegin (eventOwner event) ≤ event ∧
      event < eventStop eventCount (eventOwner event) := by
  constructor
  · exact eventBegin_owner_le event
  · rw [eventStop, Nat.lt_min]
    exact ⟨event_lt_owner_unclippedStop event, hevent⟩

/-- A half-open event interval determines its block owner uniquely. -/
theorem block_eq_eventOwner
    {block event : ℕ}
    (hbegin : eventBegin block ≤ event)
    (hstop : event < eventBegin block + eventsPerBlock) :
    block = eventOwner event := by
  apply Eq.symm
  apply Nat.div_eq_of_lt_le
  · simpa [eventBegin] using hbegin
  · simpa [eventBegin, Nat.add_mul] using hstop

/-- A capacity-sized roster contains the owner of every in-range event. -/
theorem eventOwner_lt_slots
    {eventCount event : ℕ}
    (hcapacity :
      eventCount ≤ blockSlotsPerPrime * eventsPerBlock)
    (hevent : event < eventCount) :
    eventOwner event < blockSlotsPerPrime := by
  rw [eventOwner, Nat.div_lt_iff_lt_mul]
  · exact lt_of_lt_of_le hevent hcapacity
  · norm_num [eventsPerBlock, threadsPerBlock, iterationsPerThread]

/-- For a segment within the native launch cap and a prime at least two, the
kernel's exact multiple-count formula fits the 512 block slots. -/
theorem multipleEventCount_le_capacity
    {count firstOffset prime : ℕ}
    (hcount : count ≤ maximumSegmentRows)
    (hprime : 2 ≤ prime) :
    multipleEventCount count firstOffset prime ≤
      blockSlotsPerPrime * eventsPerBlock := by
  unfold multipleEventCount
  split
  · simp
  · let capacity := blockSlotsPerPrime * eventsPerBlock
    have hcapacityPos : 0 < capacity := by
      norm_num [capacity, blockSlotsPerPrime, eventsPerBlock,
        threadsPerBlock, iterationsPerThread]
    have hcountBound : count ≤ 2 * capacity := by
      simpa [maximumSegmentRows, capacity, Nat.mul_assoc] using hcount
    have hnumerator :
        count - 1 - firstOffset < 2 * capacity := by
      omega
    have hscaled : 2 * capacity ≤ capacity * prime := by
      simpa [Nat.mul_comm] using
        Nat.mul_le_mul_left capacity hprime
    have hquotient :
        (count - 1 - firstOffset) / prime < capacity := by
      have hprimePos : 0 < prime :=
        lt_of_lt_of_le
          (by norm_num [residueSuffixMinimumPrime]) hprime
      apply (Nat.div_lt_iff_lt_mul hprimePos).2
      exact lt_of_lt_of_le hnumerator hscaled
    omega

/-- After the residue-235 seed, every admitted suffix prime is at least seven,
so the exact 147-slot minimum covers the unchanged public launch domain. -/
theorem residueMultipleEventCount_le_minimumCapacity
    {count firstOffset prime : ℕ}
    (hcount : count ≤ maximumSegmentRows)
    (hprime : residueSuffixMinimumPrime ≤ prime) :
    multipleEventCount count firstOffset prime ≤
      residueMinimumBlockSlotsPerPrime * eventsPerBlock := by
  unfold multipleEventCount
  split
  · simp
  · let capacity :=
      residueMinimumBlockSlotsPerPrime * eventsPerBlock
    have hcapacityPos : 0 < capacity := by
      norm_num [capacity, residueMinimumBlockSlotsPerPrime,
        eventsPerBlock, threadsPerBlock, iterationsPerThread]
    have hmaximumBound :
        maximumSegmentRows ≤
          residueSuffixMinimumPrime * capacity := by
      norm_num [maximumSegmentRows, residueSuffixMinimumPrime,
        capacity, residueMinimumBlockSlotsPerPrime,
        blockSlotsPerPrime, eventsPerBlock, threadsPerBlock,
        iterationsPerThread]
    have hnumerator :
        count - 1 - firstOffset <
          residueSuffixMinimumPrime * capacity := by
      omega
    have hscaled :
        residueSuffixMinimumPrime * capacity ≤
          capacity * prime := by
      simpa [Nat.mul_comm] using
        Nat.mul_le_mul_left capacity hprime
    have hquotient :
        (count - 1 - firstOffset) / prime < capacity := by
      have hprimePos : 0 < prime :=
        lt_of_lt_of_le
          (by norm_num [residueSuffixMinimumPrime]) hprime
      apply (Nat.div_lt_iff_lt_mul hprimePos).2
      exact lt_of_lt_of_le hnumerator hscaled
    omega

/-- Every admitted multiple event generates an in-segment row offset. -/
theorem multipleOffset_lt_count
    {count firstOffset prime event : ℕ}
    (hfirst : firstOffset < count)
    (hevent :
      event < multipleEventCount count firstOffset prime) :
    multipleOffset firstOffset prime event < count := by
  have heventBound :
      event ≤ (count - 1 - firstOffset) / prime := by
    rw [multipleEventCount, if_neg (Nat.not_le_of_lt hfirst)] at hevent
    omega
  have hscaled :
      event * prime ≤
        ((count - 1 - firstOffset) / prime) * prime :=
    Nat.mul_le_mul_right prime heventBound
  have hquotient :
      ((count - 1 - firstOffset) / prime) * prime ≤
        count - 1 - firstOffset :=
    Nat.div_mul_le_self _ _
  simp only [multipleOffset]
  omega

/-- Conversely, every generated prime multiple whose row offset is inside
the segment has an event ordinal in the canonical roster. -/
theorem event_lt_multipleEventCount
    {count firstOffset prime event : ℕ}
    (hfirst : firstOffset < count)
    (hprime : 0 < prime)
    (hoffset : multipleOffset firstOffset prime event < count) :
    event < multipleEventCount count firstOffset prime := by
  have hscaled :
      event * prime ≤ count - 1 - firstOffset := by
    simp only [multipleOffset] at hoffset
    have hadd :
        event * prime + firstOffset ≤ count - 1 := by
      omega
    exact Nat.le_sub_of_add_le hadd
  have heventBound :
      event ≤ (count - 1 - firstOffset) / prime :=
    (Nat.le_div_iff_mul_le hprime).2 hscaled
  rw [multipleEventCount, if_neg (Nat.not_le_of_lt hfirst)]
  omega

/-- Distinct event ordinals produce distinct row offsets for a positive
prime, so the schedule cannot process one `(prime,multiple)` pair twice. -/
theorem multipleOffset_injective
    {firstOffset prime firstEvent secondEvent : ℕ}
    (hprime : 0 < prime)
    (hequality :
      multipleOffset firstOffset prime firstEvent =
        multipleOffset firstOffset prime secondEvent) :
    firstEvent = secondEvent := by
  simp only [multipleOffset] at hequality
  apply Nat.mul_right_cancel hprime
  exact Nat.add_left_cancel hequality

end SparkInterval.TernaryGoldbach.MobiusDenseSchedule
