/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.Execution.PhalaTdxAttestation

/-!
# The Phala prod5 CH25 Lemma A.7 enclave pin and receipt, as literals

**GENERATED BY `tools/tg_phala_tdx_pin_from_evidence.py` -- DO NOT EDIT BY
HAND.**  Regenerate with

```
python3 tools/tg_phala_tdx_pin_from_evidence.py \
    --evidence-dir tests/data/phala_tdx_prod5 \
    --out SparkInterval/Execution/PhalaTdxProd5Evidence.lean
```

`tests/test_phala_tdx_prod5_pin.py` fails if this file drifts from the
evidence, and the generator refuses to emit anything unless the enclave's
signature verifies, the report-data commitment binds the quote to that key,
and the app id and app-compose hash agree across the signed receipt, the job
scope, the prelude summary and the RTMR3 event-log replay.

## Which deployment this is

One run, and only one:

* Phala Cloud **prod5**, CVM `a7-e2e`, Intel TDX, 2026-07-27T21:48:16Z.
* dstack application id `8428181231415b81042d93de854c0d82b1dab95b`,
  instance `b31dd35ed27151619cd3f67b66194cc7d16d379f`.
* app-compose hash
  `fe27ae910ef7f6760e08eb650e832b076693654deff83418a2a8ea9c9e06cdfd`,
  measured into RTMR3 and reproduced by replaying the retained dstack event
  log.
* OCI image `sha256:4e6029a39771bd18f9e0b9bc64017393700ce47c17a678dd93cbf0ddc17c774f`.
* `MRTD` `f06dfda6dce1cf904d4e2bab1dc370634cf95cefa2ceb2de2eee127c9382698090d7a4a13e14c536ec6c9c3c8fa87077`.
* `dcap-qvl v0.6.1` appraised the retained quote against the reviewed policy
  and reported `Quote verified`, TCB `UpToDate`, no advisories.
* `dcap-qvl verify --strict` did **not** pass: Getting collateral from
  https://pccs.phala.network... Error: Failed to verify quote Caused by: 0:
  Strict policy validation failed 1: Dynamic platform is not allowed by
  policy  The reviewed policy sets `require_dcap_qvl_strict: false` and
  records why; the ungated floor is the plain `verify` above, which is the
  full cryptographic appraisal, and it passed.

The retained evidence is committed at `tests/data/phala_tdx_prod5/`.

## What the literals below do and do not license

`ch25A7BoundaryPhalaProd5V1` carries `attestationAuthority := true`.  That is
the project's trust-boundary statement about **this deployment and no other**:
that the P-256 public key below was derived by dstack inside that TD and never
left it.  It licenses nothing about any other app id, any other image, or any
future run of the same image on a different platform, and it does not make the
still-unpinned `ch25A7BoundaryProductionV1` reachable.

`ch25A7BoundaryPhalaProd5TamperedKeyV1` is the same pin with one hexadecimal
digit of the public key changed.  It exists only so that
`SparkInterval/Tests/PhalaTdxProd5RunTest.lean` can state, as a Lean theorem,
that the acceptance check *rejects* it.  It carries no attestation authority.
-/

set_option autoImplicit false

namespace SparkInterval.Execution

namespace PhalaTdxProd5

/-- The reviewed pin literals for the Phala prod5 deployment, derived from
`tests/data/phala_tdx_prod5/` rather than transcribed. -/
def pin : PhalaTdxEnclavePin := {
  pinId := "sparkinterval.phala-tdx.ch25-a7-boundary.phala-prod5.v1"
  appId := "8428181231415b81042d93de854c0d82b1dab95b"
  composeHash :=
    "fe27ae910ef7f6760e08eb650e832b076693654deff83418a2a8ea9c9e06cdfd"
  imageDigest :=
    "sha256:4e6029a39771bd18f9e0b9bc64017393700ce47c17a678dd93cbf0ddc17c774f"
  enclavePublicKeyHex :=
    "04102c134190b19efac1e997ff9ab48d517506e14127660704853f2eaa5ae147" ++
    "1f97e2a83645f0f31c14efa912801318e063533b03022a7bf91c08201a84f0222d"
  quoteAppraisalPolicyHash :=
    "9de162db5c359ebc75264d90dd243ea443a2f0d765cb469c31fb57fc21f1a501"
  quoteAppraisalArtifactHash :=
    "cf7f9aaad376230844aad27bb2615377e9c622f334904c1aa35f9f74a78b9ef8"
  attestationAuthority := true
}

/-- The same pin with the final hexadecimal digit of the enclave public key
changed.  A negative-test fixture; never an identity to trust. -/
def negativeTestPin : PhalaTdxEnclavePin := {
  pinId := "sparkinterval.phala-tdx.ch25-a7-boundary.prod5-negative-test.v1"
  appId := "8428181231415b81042d93de854c0d82b1dab95b"
  composeHash :=
    "fe27ae910ef7f6760e08eb650e832b076693654deff83418a2a8ea9c9e06cdfd"
  imageDigest :=
    "sha256:4e6029a39771bd18f9e0b9bc64017393700ce47c17a678dd93cbf0ddc17c774f"
  enclavePublicKeyHex :=
    "04102c134190b19efac1e997ff9ab48d517506e14127660704853f2eaa5ae147" ++
    "1f97e2a83645f0f31c14efa912801318e063533b03022a7bf91c08201a84f02220"
  quoteAppraisalPolicyHash :=
    "9de162db5c359ebc75264d90dd243ea443a2f0d765cb469c31fb57fc21f1a501"
  quoteAppraisalArtifactHash :=
    "cf7f9aaad376230844aad27bb2615377e9c622f334904c1aa35f9f74a78b9ef8"
  attestationAuthority := false
}

/-- The receipt the enclave signed inside the TD, field for field. -/
def receipt : PhalaTdxReceipt := {
  algorithmId := "sparkinterval.ternary-goldbach.ch25-lemma-a7-boundary.v1"
  algorithmHash :=
    "340dc36f2ceb992ab16e34c534cd97b786d348ba057e159c295b3abd1328cdfa"
  inputHash :=
    "4e45410d2d26467dbd5f78f8ea536b1a8bbf44f1cd5248e234b985bd1f595674"
  parametersHash :=
    "f377fb7b8c8d8d033083a0759841411d9bb955e919041f2a5b5be830ed69212e"
  domainHash :=
    "629d9c7b3c084ef33f69d92abbe22b5120bac210fc963191c4b1e8289ff1dea5"
  result := "true"
  outputHash :=
    "b5bea41b6c623f7c09f1bf24dcae58ebab3c0cdd90ad966bc43a45b44867e12b"
  challengeNonce :=
    "563d3914c3bdd18d0602bbaf9365d7ec44190f314cf0769468900ff0c7e2e804"
  jobBindingHash :=
    "5b554fca4d1dbdb9ddf8d219e9f3226723ae1b3fcf3b2165bdd0bfe82bcd6dd7"
  appId := "8428181231415b81042d93de854c0d82b1dab95b"
  composeHash :=
    "fe27ae910ef7f6760e08eb650e832b076693654deff83418a2a8ea9c9e06cdfd"
  imageDigest :=
    "sha256:4e6029a39771bd18f9e0b9bc64017393700ce47c17a678dd93cbf0ddc17c774f"
  quoteHash :=
    "41d6ff6ac3de51cf2c6a93dc0f30a5f4e6dd39af7fa79baef1a0ee552bf79fa6"
  quoteAppraisalHash :=
    "491a2ec7098fc8e54f7b6a0eea3650d0245a7117a193316d53c6736ad119b266"
  quoteAppraisalPolicyHash :=
    "9de162db5c359ebc75264d90dd243ea443a2f0d765cb469c31fb57fc21f1a501"
  quoteAppraisalArtifactHash :=
    "cf7f9aaad376230844aad27bb2615377e9c622f334904c1aa35f9f74a78b9ef8"
  reportDataHash :=
    "976fc855805dff70d345e05e78521a16cfa80ad26f32cfa7e3c88428e96c1fc1"
  issuedAt := "2026-07-27T21:48:16Z"
  signatureHex :=
    "e5a0cab803131657257888f5fe31dae9e6d9e1a9e24b4450372307860e8a5e6b" ++
    "50088cb85723ae659c02a3bca5d3e965684f60e2c2f2d386e61e2ec3077027b7"
}

/-- The dstack-derived SEC1 uncompressed P-256 public key, spelled out so a
kernel check does no structure projection of its own. -/
def enclavePublicKeyHex : String :=
  "04102c134190b19efac1e997ff9ab48d517506e14127660704853f2eaa5ae147" ++
  "1f97e2a83645f0f31c14efa912801318e063533b03022a7bf91c08201a84f0222d"

/-- The enclave's `r || s` signature over `statementDigest`. -/
def signatureHex : String :=
  "e5a0cab803131657257888f5fe31dae9e6d9e1a9e24b4450372307860e8a5e6b" ++
  "50088cb85723ae659c02a3bca5d3e965684f60e2c2f2d386e61e2ec3077027b7"

/-- SHA-256 of the canonical signed payload, as the enclave reported it.
`receipt.statementDigest` recomputes it from the fields above. -/
def statementDigest : String :=
  "67a65b5a9c29151048d1ed5dfed0a6e4e175a794721654d90e6fbb8408a90dab"

/-- The enclave public key with its final hexadecimal digit changed. -/
def tamperedPublicKeyHex : String :=
  "04102c134190b19efac1e997ff9ab48d517506e14127660704853f2eaa5ae147" ++
  "1f97e2a83645f0f31c14efa912801318e063533b03022a7bf91c08201a84f02220"

/-- The enclave signature with its final hexadecimal digit changed. -/
def tamperedSignatureHex : String :=
  "e5a0cab803131657257888f5fe31dae9e6d9e1a9e24b4450372307860e8a5e6b" ++
  "50088cb85723ae659c02a3bca5d3e965684f60e2c2f2d386e61e2ec3077027b0"

/-- The statement digest obtained by altering only `issuedAt`, the one
signed field no check other than the signature itself inspects. -/
def tamperedStatementDigest : String :=
  "51c2c852f2c6d1ab586a2d0128da9d2a32e86f890d57d625f3bd905304778eff"

/-- The altered `issuedAt` that produces `tamperedStatementDigest`. -/
def tamperedIssuedAt : String :=
  "2026-07-27T21:48:10Z"

/-- The app id with its final hexadecimal digit changed. -/
def tamperedAppId : String :=
  "8428181231415b81042d93de854c0d82b1dab950"

/-- The app-compose hash with its final hexadecimal digit changed: a
different measured code base. -/
def tamperedComposeHash : String :=
  "fe27ae910ef7f6760e08eb650e832b076693654deff83418a2a8ea9c9e06cdf0"

end PhalaTdxProd5

/-- The hand-written pin case in `Execution/PhalaTdxAttestation.lean` is
exactly the machine-derived one.  A single mistyped hexadecimal digit in
either copy fails this `decide`, which is the point: the 130-character public
key is never trusted to a human's eyes. -/
theorem phalaTdxProd5_pin_eq_generated :
    PhalaTdxEnclave.ch25A7BoundaryPhalaProd5V1.pin = PhalaTdxProd5.pin := by
  decide

/-- Likewise for the negative-test fixture. -/
theorem phalaTdxProd5_negativeTestPin_eq_generated :
    PhalaTdxEnclave.ch25A7BoundaryPhalaProd5TamperedKeyV1.pin
      = PhalaTdxProd5.negativeTestPin := by
  decide

/-- The pinned key is the one the enclave published. -/
theorem phalaTdxProd5_pin_publicKey :
    PhalaTdxEnclave.ch25A7BoundaryPhalaProd5V1.pin.enclavePublicKeyHex
      = PhalaTdxProd5.enclavePublicKeyHex := by
  decide

/-- The receipt carries the signature spelled out above. -/
theorem phalaTdxProd5_receipt_signature :
    PhalaTdxProd5.receipt.signatureHex = PhalaTdxProd5.signatureHex := by
  decide

/-- **The trust-boundary flag.**  This is the one deployment the project
treats as an Intel TDX attestation authority. -/
theorem phalaTdxProd5_has_attestationAuthority :
    PhalaTdxEnclave.ch25A7BoundaryPhalaProd5V1.pin.attestationAuthority
      = true := by
  decide

/-- The negative-test fixture never does. -/
theorem phalaTdxProd5_negativeTest_no_authority :
    PhalaTdxEnclave.ch25A7BoundaryPhalaProd5TamperedKeyV1.pin.attestationAuthority
      = false := by
  decide

/-- Installing the prod5 identity left the older, deliberately empty
production pin exactly as it was: still unreachable. -/
theorem phalaTdxProd5_leaves_productionV1_unpinned :
    PhalaTdxEnclave.ch25A7BoundaryProductionV1.pin.enclavePublicKeyHex
      = "" := by
  decide

end SparkInterval.Execution
