import SparkInterval.EvalSound
import SparkInterval.ComplexInterval
import SparkInterval.FPIntervalSound
import SparkInterval.PTX.Semantics
import SparkInterval.PTX.MachineSemantics
import SparkInterval.PTX.CodeComposition
import SparkInterval.PTX.F64RegisterEffects
import SparkInterval.PTX.InstructionRefinement
import SparkInterval.PTX.ExpressionInstructionRefinement
import SparkInterval.PTX.CompilerDataflow
import SparkInterval.PTX.CompilerFiniteGuardRefinement
import SparkInterval.PTX.CompilerNodeRefinement
import SparkInterval.PTX.CompilerOutputRefinement
import SparkInterval.PTX.PrologueRefinement
import SparkInterval.PTX.OutputLayoutRefinement
import SparkInterval.PTX.GeneratedKernelRunRefinement
import SparkInterval.PTX.Emitter
import SparkInterval.PTX.NvidiaPTXRefinement
import SparkInterval.PTX.PowSchedule
import SparkInterval.PTX.StructuralCompilerCorrect
import SparkInterval.Certificate
import SparkInterval.Execution.FormalPTXProgram
import SparkInterval.Execution.RegisteredAlgorithm
import SparkInterval.Execution.SignedZetaEndpointPayload
import SparkInterval.Zeta.EndpointCertificate
import SparkInterval.Zeta.EvenReflectionCertificate
import SparkInterval.Zeta.HardyZContract
import SparkInterval.Zeta.MultiplicityCount
import SparkInterval.Zeta.StreamingEndpointCertificate
import SparkInterval.Zeta.StreamingChunkVerifier
import SparkInterval.Zeta.SymmetricCount

/-!
The output of these commands is part of the mathematical-core and Phase 8
audit surface. No project postulate is declared; only Lean/Mathlib's standard
logical foundations may appear. Concrete generated serialized-certificate
modules print their separate `native_decide` dependency in the generated file.
-/

#print axioms SparkInterval.RealInterval.add_contains
#print axioms SparkInterval.RealInterval.mul_contains
#print axioms SparkInterval.RealInterval.reciprocal_contains
#print axioms SparkInterval.RealInterval.div_contains
#print axioms SparkInterval.ComplexInterval.mul_contains
#print axioms SparkInterval.ComplexInterval.powNat_contains
#print axioms SparkInterval.evalInterval_sound
#print axioms SparkInterval.Binary64Rounding.roundDown_le
#print axioms SparkInterval.Binary64Rounding.le_roundUp
#print axioms SparkInterval.Binary64Rounding.roundDown_greatest
#print axioms SparkInterval.Binary64Rounding.roundUp_least
#print axioms SparkInterval.FPInterval.add_contains
#print axioms SparkInterval.FPInterval.sub_contains
#print axioms SparkInterval.FPInterval.mul_contains
#print axioms SparkInterval.FPInterval.div_contains
#print axioms SparkInterval.PTX.directedBinary_down_le
#print axioms SparkInterval.PTX.le_directedBinary_up
#print axioms SparkInterval.PTX.decodeF64Bits_of_finite
#print axioms SparkInterval.PTX.decodeF64Bits_of_infinite
#print axioms SparkInterval.PTX.decodeF64Bits_of_nan
#print axioms SparkInterval.PTX.addFragmentResult_contains
#print axioms SparkInterval.PTX.subFragmentResult_contains
#print axioms SparkInterval.PTX.mulFragmentResult_contains
#print axioms SparkInterval.PTX.executeCanonicalAdd_contains
#print axioms SparkInterval.PTX.executeCanonicalSub_contains
#print axioms SparkInterval.PTX.executeCanonicalMul_contains
#print axioms SparkInterval.PTX.PolynomialExpr.evalKernel_sound
#print axioms SparkInterval.PTX.ThreadContext.globalIndex_eq
#print axioms SparkInterval.PTX.globalAddress_eq_of_lt
#print axioms SparkInterval.PTX.executeCode_append
#print axioms SparkInterval.PTX.executeCode_append_fallthrough
#print axioms SparkInterval.PTX.executeCode_append_jump
#print axioms SparkInterval.PTX.executeCode_append_returned
#print axioms SparkInterval.PTX.executeInstruction_preserves_f64_read
#print axioms SparkInterval.PTX.executeCode_preserves_f64_read
#print axioms SparkInterval.PTX.executeFiniteGuard_fallthrough
#print axioms SparkInterval.PTX.executeFiniteGuard_lowerNonfinite
#print axioms SparkInterval.PTX.executeFiniteGuard_upperNonfinite
#print axioms SparkInterval.PTX.executeAddArithmeticFragment
#print axioms SparkInterval.PTX.executeSubArithmeticFragment
#print axioms SparkInterval.PTX.executeMulArithmeticFragment
#print axioms SparkInterval.PTX.executeConstInstructions
#print axioms SparkInterval.PTX.executeLoadIntervalInstructions
#print axioms SparkInterval.PTX.executeNegInstructions
#print axioms SparkInterval.PTX.emitFiniteGuard_body
#print axioms SparkInterval.PTX.emitFiniteGuard_body_size
#print axioms SparkInterval.PTX.executeCompiledFiniteGuard_fallthrough
#print axioms SparkInterval.PTX.executeCompiledFiniteGuard_lowerNonfinite
#print axioms SparkInterval.PTX.executeCompiledFiniteGuard_upperNonfinite
#print axioms SparkInterval.PTX.allocateMulRegisters_destinationIndices_nodup
#print axioms SparkInterval.PTX.compileMul_refinement_freshness
#print axioms SparkInterval.PTX.compileExpr_nextF64
#print axioms SparkInterval.PTX.compileExpr_result_below
#print axioms SparkInterval.PTX.compileExpr_pair_below
#print axioms SparkInterval.PTX.compileMulAllocation_destinationIndices_eq
#print axioms SparkInterval.PTX.executeCompileAddArithmeticFragment
#print axioms SparkInterval.PTX.executeCompileSubArithmeticFragment
#print axioms SparkInterval.PTX.executeCompileMulArithmeticFragment
#print axioms SparkInterval.PTX.executeCompileExprAppendedCode
#print axioms SparkInterval.PTX.emitOutput_body
#print axioms SparkInterval.PTX.writeOutputMemory_contains
#print axioms SparkInterval.PTX.executeCompiledOutput
#print axioms SparkInterval.PTX.executeCompiledOutput_contains
#print axioms SparkInterval.PTX.executeCompiledOutput_observe
#print axioms SparkInterval.PTX.emitPrologue_exact
#print axioms SparkInterval.PTX.executePrologue_outOfRange
#print axioms SparkInterval.PTX.executePrologue_inRange
#print axioms SparkInterval.PTX.executePrologue_inRange_exactNat
#print axioms SparkInterval.PTX.prologueOutputBase_record_safe
#print axioms SparkInterval.PTX.observeOutput_eq_prologueOutputBase
#print axioms SparkInterval.PTX.executeCompiledOutput_observeRow
#print axioms SparkInterval.PTX.executeBuildModuleStructured_inRange
#print axioms SparkInterval.PTX.runBuildModule_outOfRange
#print axioms SparkInterval.PTX.runBuildModule_inRange
#print axioms SparkInterval.PTX.runBuildModule_inRange_containsReal
#print axioms SparkInterval.PTX.buildModule_opcodeTrace
#print axioms SparkInterval.PTX.StructuralCompilerCorrect.buildModule_eq_expectedModule
#print axioms SparkInterval.PTX.Instruction.opcode_mem_allowed
#print axioms SparkInterval.PTX.emit_success
#print axioms SparkInterval.PTX.emit_of_validate
#print axioms SparkInterval.PTX.runPowSchedule_eq_pow
#print axioms SparkInterval.PTX.NvidiaPTX90.allowedOpcode_has_pinned_clause
#print axioms SparkInterval.PTX.NvidiaPTX90.acceptedInstruction_has_pinned_clause
#print axioms SparkInterval.PTX.NvidiaPTX90.division_not_in_current_allowlist
#print axioms SparkInterval.PTX.NvidiaPTX90.evalFinite_towardNegative_le
#print axioms SparkInterval.PTX.NvidiaPTX90.le_evalFinite_towardPositive
#print axioms SparkInterval.PTX.NvidiaPTX90.directedBinary_finite_refines
#print axioms SparkInterval.PTX.NvidiaPTX90.minimum_nonNaN_refines
#print axioms SparkInterval.PTX.NvidiaPTX90.maximum_nonNaN_refines
#print axioms SparkInterval.PTX.NvidiaPTX90.executeInstruction_binaryF64_finite_refines
#print axioms SparkInterval.PTX.NvidiaPTX90.executeInstruction_minimumF64_nonNaN_refines
#print axioms SparkInterval.PTX.NvidiaPTX90.executeInstruction_maximumF64_nonNaN_refines
#print axioms SparkInterval.PTX.NvidiaPTX90.renderUnchecked_startsWith_dgxSparkProfile
#print axioms SparkInterval.PTX.NvidiaPTX90.renderUncheckedH100_startsWith_h100Profile
#print axioms SparkInterval.PTX.NvidiaPTX90.buildModule_opcodeTrace_all_have_pinned_clauses
#print axioms SparkInterval.PTX.NvidiaPTX90.buildModule_has_partial_ptx90_evidence
#print axioms SparkInterval.PTX.NvidiaPTX90.buildModule_has_partial_ptx90_evidenceFor
#print axioms SparkInterval.Execution.FormalPTXProgram.statementCheck_sound
#print axioms SparkInterval.Execution.FormalPTXProgram.emitted_eq_renderUnchecked
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicSumDivThree_eq_closedForm
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicSumDivThree_20000
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicNumeratorLoop_cast
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicSumDivThreeMachine_20000
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicSumDivThreeMachine_sound_20000
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicNumeratorLoop_lt_u64
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cube_lt_u64
#print axioms SparkInterval.Execution.RegisteredAlgorithm.square_lt_u64
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicNumeratorStep_lt_u64
#print axioms SparkInterval.Execution.RegisteredAlgorithm.cubicSumDivThreeMachine_lt_u64
#print axioms SparkInterval.Execution.RegisteredInvocation.statementCheck_sound
#print axioms SparkInterval.Execution.RegisteredInvocation.cubicSumDivThree20000V1_output
#print axioms SparkInterval.Zeta.RationalBracketFamily.exists_zeroCertificate
#print axioms SparkInterval.Zeta.ZeroCertificate.complete_of_count_upperBound
#print axioms SparkInterval.Zeta.ChunkCertificate.complete_of_count_upperBound
#print axioms SparkInterval.Zeta.all_zeros_to_height_on_criticalLine
#print axioms SparkInterval.Zeta.ZetaVerifierEvidence.all_zeros_on_criticalLine
#print axioms SparkInterval.Zeta.ChunkedZetaVerifierEvidence.all_zeros_on_criticalLine
#print axioms SparkInterval.Zeta.HardyZModel.zero_iff
#print axioms SparkInterval.Zeta.HardyZModel.verifyEndpointFamily
#print axioms SparkInterval.Zeta.one_le_zetaZeroMultiplicity
#print axioms SparkInterval.Zeta.coe_ncard_le_zetaZeroMultiplicityCount
#print axioms SparkInterval.Zeta.ZetaMultiplicityCountUpperBound.distinctCount_le
#print axioms SparkInterval.Zeta.ZetaMultiplicityCountUpperBound.toZetaZeroCountUpperBound
#print axioms SparkInterval.Zeta.ZetaMultiplicityCountCertificate.check_sound
#print axioms SparkInterval.Certificate.RawInterval.decodeOutput_of_decodeFinite
#print axioms SparkInterval.Certificate.FullCertificate.resultContains_of_decodeFinite
#print axioms SparkInterval.Execution.SignedZetaEndpointPayload.CheckedPayload.enclosesEndpoints
#print axioms SparkInterval.Execution.SignedZetaEndpointPayload.batchBindingCheck_sound
#print axioms SparkInterval.Zeta.runEndpointChunk_append
#print axioms SparkInterval.Zeta.checkEndpointStream_isValid
#print axioms SparkInterval.Zeta.RationalBracket.reflect_isValid_iff
#print axioms SparkInterval.Zeta.RationalBracketFamily.reflectPositive_isValid
#print axioms SparkInterval.Zeta.RationalBracketFamily.reflectPositive_enclosesEndpoints
#print axioms SparkInterval.Zeta.runEndpointChunkStream_append
#print axioms SparkInterval.Zeta.exists_checkedEndpointChunkCertificate
#print axioms SparkInterval.Zeta.verifyEndpointChunkStream
#print axioms SparkInterval.Zeta.zetaZeroMultiplicityCount_partition
#print axioms SparkInterval.Zeta.ZetaConjugationMultiplicitySymmetry.negative_eq_positive
#print axioms SparkInterval.Zeta.PositiveZetaMultiplicityCountUpperBound.toZetaMultiplicityCountUpperBound
#print axioms SparkInterval.Certificate.CertExpr.eval_sound
#print axioms SparkInterval.Certificate.FullCertificate.check_sound
#print axioms SparkInterval.Certificate.FullCertificate.checkUpperBound_sound
#print axioms SparkInterval.Certificate.FullCertificate.checkSumUpperBound_sound
#print axioms SparkInterval.Certificate.impliesTheorem
#print axioms SparkInterval.Certificate.impliesSumTheorem
