# Copyright (c) 2026 Gershon Bialer. All rights reserved.
# SPDX-License-Identifier: MIT

"""Exact reference and artifact helpers for ternary-Goldbach campaigns.

The package contains CPU references, certificate-format primitives, and the
checked thirteen-atom catalog.  It does not, by itself, certify that any
production computation has run or discharge a Lean trust atom.
"""

from .arithmetic import (
    ARITHMETIC_ATOMS,
    CDEM_ABEL_ATOM,
    CDEM_ABEL_ALGORITHM,
    CDEM_SQUAREFREE_ATOM,
    CDEM_SQUAREFREE_ALGORITHM,
    HURST_MERTENS_ATOM,
    HURST_MERTENS_ALGORITHM,
    PLATT_2_11_ATOM,
    PLATT_2_11_ALGORITHM,
    PLATT_STRONGER_ATOM,
    PLATT_STRONGER_ALGORITHM,
    RAMARE_ZUNIGA_R2STAR_ATOM,
    RAMARE_ZUNIGA_R2STAR_ALGORITHM,
    ZERO_SHA256,
    ChainVerification,
    ChunkRecord,
    ChunkVerificationError,
    HurstSampleResult,
    LittleMertensBound,
    LittleMertensSampleResult,
    SquarefreeEndpointClassification,
    SquarefreeSampleResult,
    check_chunk_chain,
    check_hurst_sample,
    check_hurst_squared,
    check_little_mertens_interval,
    check_little_mertens_sample,
    check_squarefree_sample,
    classify_squarefree_endpoint,
    create_chunk_record,
    hurst_squared_slack,
    little_mertens_interval_slack,
    little_mertens_prefix_sums,
    mobius_linear,
    mobius_segment,
    squarefree_prefix_counts,
    verify_chunk_chain,
)
from .catalog import ATOMS, ATOMS_BY_ID, AtomSpec, CatalogError, load_catalog
from .mobius_cuda import (
    LITTLE_MERTENS_2_11_LIMIT,
    LITTLE_MERTENS_SCALE,
    LITTLE_MERTENS_SCALE_BITS,
    LITTLE_MERTENS_STRONGER_LIMIT,
    MobiusChainResult,
    MobiusReceiptError,
    little_mertens_fixed_point_increment,
    little_mertens_fixed_point_squared_slack,
    verify_mobius_receipt,
    verify_mobius_receipt_chain,
)

__all__ = [
    "ATOMS",
    "ATOMS_BY_ID",
    "ARITHMETIC_ATOMS",
    "AtomSpec",
    "CDEM_ABEL_ATOM",
    "CDEM_ABEL_ALGORITHM",
    "CDEM_SQUAREFREE_ATOM",
    "CDEM_SQUAREFREE_ALGORITHM",
    "HURST_MERTENS_ATOM",
    "HURST_MERTENS_ALGORITHM",
    "PLATT_2_11_ATOM",
    "PLATT_2_11_ALGORITHM",
    "PLATT_STRONGER_ATOM",
    "PLATT_STRONGER_ALGORITHM",
    "RAMARE_ZUNIGA_R2STAR_ATOM",
    "RAMARE_ZUNIGA_R2STAR_ALGORITHM",
    "ZERO_SHA256",
    "ChainVerification",
    "ChunkRecord",
    "ChunkVerificationError",
    "CatalogError",
    "HurstSampleResult",
    "LittleMertensBound",
    "LittleMertensSampleResult",
    "LITTLE_MERTENS_2_11_LIMIT",
    "LITTLE_MERTENS_SCALE",
    "LITTLE_MERTENS_SCALE_BITS",
    "LITTLE_MERTENS_STRONGER_LIMIT",
    "MobiusChainResult",
    "MobiusReceiptError",
    "SquarefreeEndpointClassification",
    "SquarefreeSampleResult",
    "check_chunk_chain",
    "check_hurst_sample",
    "check_hurst_squared",
    "check_little_mertens_interval",
    "check_little_mertens_sample",
    "check_squarefree_sample",
    "classify_squarefree_endpoint",
    "create_chunk_record",
    "hurst_squared_slack",
    "little_mertens_interval_slack",
    "little_mertens_prefix_sums",
    "little_mertens_fixed_point_increment",
    "little_mertens_fixed_point_squared_slack",
    "load_catalog",
    "mobius_linear",
    "mobius_segment",
    "squarefree_prefix_counts",
    "verify_chunk_chain",
    "verify_mobius_receipt",
    "verify_mobius_receipt_chain",
]
