#!/usr/bin/env python3
# Copyright (c) 2026 Gershon Bialer. All rights reserved.
# SPDX-License-Identifier: MIT

"""Generate the small V2 Pratt/gap certificate used by the Möbius sieve."""

from __future__ import annotations

import argparse
import math
from pathlib import Path


def smallest_prime_factors(bound: int) -> list[int]:
    factors = list(range(bound + 1))
    if bound >= 1:
        factors[1] = 1
    for prime in range(2, math.isqrt(bound) + 1):
        if factors[prime] != prime:
            continue
        for value in range(prime * prime, bound + 1, prime):
            if factors[value] == value:
                factors[value] = prime
    return factors


def factorization(value: int, smallest: list[int]) -> list[int]:
    result: list[int] = []
    while value > 1:
        factor = smallest[value]
        result.append(factor)
        value //= factor
    return result


def lucas_witness(prime: int, factors: list[int]) -> int:
    if prime == 2:
        return 0
    for witness in range(2, prime):
        if pow(witness, prime - 1, prime) != 1:
            continue
        if all(
            pow(witness, (prime - 1) // factor, prime) != 1
            for factor in dict.fromkeys(factors)
        ):
            return witness
    raise RuntimeError(f"no Lucas witness found for {prime}")


def lean_list(values: list[int]) -> str:
    return "[" + ", ".join(str(value) for value in values) + "]"


def factor_pairs(
    start: int, stop: int, smallest: list[int]
) -> str:
    rows = [
        f"pair {smallest[value]} {value // smallest[value]}"
        for value in range(start, stop)
    ]
    return "[" + ", ".join(rows) + "]"


def render(bound: int) -> str:
    if not 2 <= bound <= 65_535:
        raise ValueError("base certificate bound must be in [2,65535]")
    smallest = smallest_prime_factors(bound)
    primes = [
        value
        for value in range(2, bound + 1)
        if smallest[value] == value
    ]
    prime_indices = {
        prime: index for index, prime in enumerate(primes)
    }
    row_lines: list[str] = []
    previous = 1
    for prime in primes:
        factors = [] if prime == 2 else factorization(
            prime - 1, smallest
        )
        references = [prime_indices[factor] for factor in factors]
        witness = lucas_witness(prime, factors)
        gaps = factor_pairs(previous + 1, prime, smallest)
        row_lines.append(
            "    { prime := "
            f"{prime}, witness := {witness}, "
            f"factorRefs := {lean_list(references)}, "
            f"gapPairs := {gaps} }}"
        )
        previous = prime
    tail = factor_pairs(previous + 1, bound + 1, smallest)
    rows = ",\n".join(row_lines)
    return f"""\
/- Copyright (c) 2026 Gershon Bialer. All rights reserved.
SPDX-License-Identifier: MIT -/

import SparkInterval.TernaryGoldbach.MobiusSegmentedSieveRoster

/-!
This file is generated by `tools/generate_mobius_base_v2_lean.py`.
It contains only the short prime certificate through `{bound}` used as the
base of the production segmented-sieve roster checker.
-/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0

namespace SparkInterval.Generated.MobiusBasePrimeV2

open SparkInterval.TernaryGoldbach.MobiusPrimeRosterCertificateBridge
open SparkInterval.TernaryGoldbach.MobiusPrimeRosterCompleteness
open SparkInterval.TernaryGoldbach.MobiusSegmentedSieveRoster
open SparkInterval.TernaryGoldbach.Sqrt218Operational.V2

private def pair (left right : Nat) : FactorPair := {{ left, right }}

def certificate : PrimeRosterCertificate := {{
  rows := [
{rows}
  ]
  tailPairs := {tail}
}}

def certificateCheck : Bool :=
  primeRosterCheck {bound} certificate

theorem primeRosterThrough :
    certificateCheck = true →
      PrimeRosterThrough {bound} (rosterList certificate) := by
  intro checked
  apply primeRosterThrough_of_checkedCertificate
  simpa only [certificateCheck] using checked

/-- One production predicate with the materialized short base certificate. -/
def productionCheck
    (factorCodes : Array Nat)
    (rawFactorCodeBytes rawRosterBytes : ByteArray)
    (rawPrimes : List Nat) : Bool :=
  certifiedRosterCheck {bound} productionPrimeBound
    certificate factorCodes rawFactorCodeBytes
    rawRosterBytes rawPrimes

theorem productionCheck_sound
    {{factorCodes : Array Nat}}
    {{rawFactorCodeBytes rawRosterBytes : ByteArray}}
    {{rawPrimes : List Nat}}
    (checked :
      productionCheck factorCodes rawFactorCodeBytes
        rawRosterBytes rawPrimes = true) :
    PrimeRosterThrough productionPrimeBound rawPrimes ∧
      rawFactorCodeBytes =
        encodeFactorCodesU16LE factorCodes ∧
      rawRosterBytes = encodeRosterU32LE rawPrimes := by
  apply productionCertifiedRosterCheck_sound
  simpa only [productionCheck] using checked

#print axioms primeRosterThrough
#print axioms productionCheck_sound

end SparkInterval.Generated.MobiusBasePrimeV2
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--bound", type=int, default=10_000)
    arguments = parser.parse_args()
    output = render(arguments.bound)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(output, encoding="utf-8")
    print(
        f"bound={arguments.bound} bytes={len(output.encode('utf-8'))}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
