#!/usr/bin/env python3
"""Generate a Lean instantiation of a GRH POC certificate.

Reads the certificate JSON emitted by tools/run_grh_poc.py, selects one
character of modulus 3 or 4 (the moduli with concrete Lean characters in
SparkInterval.Dirichlet.SmallModuli), and emits a Lean file that:

1. embeds the bracket family as exact rational literals recovered from the
   serialized binary64 data;
2. proves `family.check = true` with the kernel-reducible checker (or
   `native_decide` in native mode);
3. proves the rational domain bounds `lo <= lower_i`, `upper_i <= hi`; and
4. states the conditional finite-strip GRH theorem for the modulus, with
   the analytic premises (evaluator model, endpoint enclosures, total zero
   count) as explicit hypotheses, exactly mirroring the honest premise
   structure of the Riemann zeta verifier.

The emitted theorem concludes `GRHVerifiedForModulus q lo hi`.
"""

import argparse
import hashlib
import json
import pathlib
from fractions import Fraction

CHAR_NAMES = {
    3: ("chiThree", "chiThree_ne_one", "grhVerifiedForModulus_three"),
    4: ("chiFour", "chiFour_ne_one", "grhVerifiedForModulus_four"),
}


def rat_literal(value):
    frac = Fraction(value)
    if frac.denominator == 1:
        return f"({frac.numerator} : ℚ)"
    return f"(({frac.numerator} : ℚ) / {frac.denominator})"


def hex_rat(hex_str):
    return rat_literal(Fraction(float.fromhex(hex_str)))


def bracket_literal(bracket):
    lv = bracket["lower_value"]
    uv = bracket["upper_value"]
    return ("  { lower := " + hex_rat(bracket["lower"]) + ",\n"
            "    upper := " + hex_rat(bracket["upper"]) + ",\n"
            "    lowerValue := { lo := " + hex_rat(lv["re_lo"]) +
            ", hi := " + hex_rat(lv["re_hi"]) + " },\n"
            "    upperValue := { lo := " + hex_rat(uv["re_lo"]) +
            ", hi := " + hex_rat(uv["re_hi"]) + " } }")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--certificate", required=True)
    parser.add_argument("--character-index", type=int, default=0)
    parser.add_argument("--output", required=True)
    parser.add_argument("--decision-mode", choices=["kernel", "native"],
                        default="kernel")
    args = parser.parse_args()

    payload = json.loads(pathlib.Path(args.certificate).read_text())
    q = payload["q"]
    if q not in CHAR_NAMES:
        raise SystemExit(
            f"modulus {q} has no concrete Lean character; supported: 3, 4")
    char_name, ne_one_name, modulus_theorem = CHAR_NAMES[q]
    char = payload["characters"][args.character_index]
    if char["conductor"] != q:
        raise SystemExit("selected character is imprimitive")
    brackets = char["brackets"]
    count = len(brackets)
    lo = Fraction(payload["t_lo"])
    hi = Fraction(payload["t_hi"])
    digest = hashlib.sha256(
        pathlib.Path(args.certificate).read_bytes()).hexdigest()

    check_tactic = ("decide +kernel" if args.decision_mode == "kernel"
                    else "native_decide")
    bracket_lines = ",\n".join(bracket_literal(b) for b in brackets)

    text = f"""import SparkInterval.Dirichlet.SmallModuli

/-!
# Generated GRH finite-verification certificate instantiation

Generated by tools/generate_grh_lean.py from the GPU-produced certificate
with SHA-256 `{digest}`
(algorithm `{payload["algorithm"]}`, paper {payload["paper"]}).

Modulus {q}, character exponents {char["exponents"]}, parity
{char["parity"]}, ordinate window [{payload["t_lo"]}, {payload["t_hi"]}],
{count} strict sign-change brackets isolated on the critical line, grid
step {payload["grid_step"]}, Euler-Maclaurin main-sum length
{payload["terms_m"]}, device `{payload["gpu"]}`.

The Boolean family check and the rational domain bounds are proved here
from the embedded literals.  The analytic premises (the evaluator model,
its endpoint enclosures, and the total zero-count upper bound) remain
explicit hypotheses of the final theorem, mirroring the premise structure
of the Riemann-zeta verifier in this repository.
-/

set_option autoImplicit false
set_option maxRecDepth 4096

namespace SparkInterval.Dirichlet.Generated{char_name}Cert

open SparkInterval.Zeta
open SparkInterval.Dirichlet

/-- The GPU-isolated sign-change brackets as exact rationals. -/
def grhBrackets : List RationalBracket := [
{bracket_lines}
]

theorem grhBrackets_length : grhBrackets.length = {count} := by rfl

/-- The bracket family consumed by the generic endpoint checker. -/
def grhFamily : RationalBracketFamily {count} :=
  ⟨fun i => grhBrackets.get (i.cast grhBrackets_length.symm)⟩

theorem grh_family_check : grhFamily.check = true := by
  {check_tactic}

def loQ : ℚ := {rat_literal(lo)}
def hiQ : ℚ := {rat_literal(hi)}

theorem grh_lower_bounds_rat :
    ∀ i : Fin {count}, loQ ≤ (grhFamily.entries i).lower := by
  {check_tactic}

theorem grh_upper_bounds_rat :
    ∀ i : Fin {count}, (grhFamily.entries i).upper ≤ hiQ := by
  {check_tactic}

theorem grh_lower_bounds :
    ∀ i : Fin {count}, ((loQ : ℚ) : ℝ) ≤ ((grhFamily.entries i).lower : ℝ) :=
  fun i => Rat.cast_le.mpr (grh_lower_bounds_rat i)

theorem grh_upper_bounds :
    ∀ i : Fin {count}, (((grhFamily.entries i).upper : ℚ) : ℝ) ≤ ((hiQ : ℚ) : ℝ) :=
  fun i => Rat.cast_le.mpr (grh_upper_bounds_rat i)

/-- Conditional finite-strip GRH theorem for modulus {q}.

Given a proved completed-L evaluator model for `{char_name}` on the
window, endpoint enclosures realizing the checked rows, and a total
zero-count upper bound equal to the bracket count, every zero of every
primitive Dirichlet L-function of modulus {q} in the closed rectangle
`[0,1] x [loQ, hiQ]` lies on the critical line. -/
theorem grh_modulus_{q}_finite_verification
    (f : ℝ → ℝ)
    (model : DirichletHardyModel {char_name} f (loQ : ℝ) (hiQ : ℝ))
    (hencloses : ∀ i, (grhFamily.entries i).EnclosesEndpoints f)
    (totalUpper :
      LZeroCountUpperBound {char_name} (loQ : ℝ) (hiQ : ℝ) {count}) :
    GRHVerifiedForModulus {q} (loQ : ℝ) (hiQ : ℝ) :=
  {modulus_theorem}
    (DirichletHardyModel.verifyEndpointFamily {ne_one_name} model
      grhFamily grh_family_check hencloses
      grh_lower_bounds grh_upper_bounds totalUpper)

#print axioms grh_modulus_{q}_finite_verification

end SparkInterval.Dirichlet.Generated{char_name}Cert
"""
    out = pathlib.Path(args.output)
    if out.exists():
        raise SystemExit(f"refusing to overwrite {out}")
    out.write_text(text)
    print(json.dumps({
        "kind": "sparkinterval_grh_lean_receipt",
        "certificate_sha256": digest,
        "q": q,
        "character_index": args.character_index,
        "bracket_count": count,
        "decision_mode": args.decision_mode,
        "output": str(out),
    }, indent=1))


if __name__ == "__main__":
    main()
