#!/usr/bin/env python3
"""Turn the PT21 checker's binary level-2 records into a Lean module.

This is the glue between the compiled level-0 checker
(``cpu_checker/pt21_ladder``) and the kernel-checked ladder
(``SparkInterval/Zeta/PT21Ladder.lean``).  The emitted module contains

* the literal ``List GroupSummary`` decoded from the binary records,
* the ``CampaignRecord`` implied by the first and last record, and
* ``theorem ladder_accepts : checkCampaign record groups = true := by rfl``.

Nothing here is trusted: the emitted module is checked by the Lean kernel,
and a wrong transcription simply fails to reduce to ``true``.

Usage:

    tools/tg_pt21_ladder_lean.py groups.bin --root <hex> \\
        --module SparkInterval.Zeta.PT21LadderInstance \\
        --output SparkInterval/Zeta/PT21LadderInstance.lean
"""

from __future__ import annotations

import argparse
import pathlib
import struct
import sys

GROUP_RECORD_BYTES = 88


def decode(blob: bytes) -> list[dict]:
    if len(blob) % GROUP_RECORD_BYTES != 0:
        raise SystemExit(
            "level-2 file length %d is not a multiple of %d"
            % (len(blob), GROUP_RECORD_BYTES)
        )
    records = []
    for offset in range(0, len(blob), GROUP_RECORD_BYTES):
        chunk = blob[offset : offset + GROUP_RECORD_BYTES]
        first_block, blocks, lower, slots, upper = struct.unpack_from(
            ">QQQQQ", chunk, 0
        )
        digest = chunk[40:72]
        index, reserved = struct.unpack_from(">QQ", chunk, 72)
        if reserved != 0:
            raise SystemExit("record %d has a nonzero reserved field" % index)
        if lower + slots != upper:
            raise SystemExit("record %d fails local closure" % index)
        records.append(
            {
                "first_block": first_block,
                "blocks": blocks,
                "lower": lower,
                "slots": slots,
                "upper": upper,
                "digest": digest,
                "index": index,
            }
        )
    return records


def check_chain(records: list[dict]) -> None:
    """Reject obviously broken input before asking Lean to.

    This is a convenience, not a security boundary: the Lean kernel repeats
    every one of these checks on the emitted literals.
    """
    for position, record in enumerate(records):
        if record["index"] != position:
            raise SystemExit("record %d is out of order" % position)
        if record["blocks"] == 0:
            raise SystemExit("record %d is empty" % position)
        if position + 1 < len(records):
            following = records[position + 1]
            if record["first_block"] + record["blocks"] != following["first_block"]:
                raise SystemExit("block gap after record %d" % position)
            if record["upper"] != following["lower"]:
                raise SystemExit("count gap after record %d" % position)


def digest_literal(digest: bytes) -> str:
    return "[" + ", ".join("0x%02x" % byte for byte in digest) + "]"


def emit(records: list[dict], module: str, root_hex: str) -> str:
    if not records:
        raise SystemExit("no level-2 records")
    root = bytes.fromhex(root_hex)
    if len(root) != 32:
        raise SystemExit("root must be 32 bytes")
    first = records[0]
    last = records[-1]
    total_blocks = sum(record["blocks"] for record in records)
    total_slots = sum(record["slots"] for record in records)

    lines = [
        "/- Generated by tools/tg_pt21_ladder_lean.py.  Do not edit. -/",
        "",
        "import SparkInterval.Zeta.PT21Ladder",
        "",
        "set_option maxRecDepth 4000000",
        "set_option maxHeartbeats 0",
        "",
        "namespace %s" % module,
        "",
        "open SparkInterval.Zeta.PT21Ladder",
        "",
        "def groups : List GroupSummary := [",
    ]
    entries = []
    for record in records:
        entries.append(
            "  { firstBlock := %d, blockCount := %d, lowerCount := %d,"
            "\n    slots := %d, upperCount := %d,"
            "\n    digest := %s }"
            % (
                record["first_block"],
                record["blocks"],
                record["lower"],
                record["slots"],
                record["upper"],
                digest_literal(record["digest"]),
            )
        )
    lines.append(",\n".join(entries))
    lines.append("]")
    lines.append("")
    lines.append("def record : CampaignRecord := {")
    lines.append("  firstBlock := %d" % first["first_block"])
    lines.append("  blockCount := %d" % total_blocks)
    lines.append("  lowerCount := %d" % first["lower"])
    lines.append("  slots := %d" % total_slots)
    lines.append("  upperCount := %d" % last["upper"])
    lines.append("  root := %s" % digest_literal(root))
    lines.append("}")
    lines.append("")
    lines.append(
        "/-- Kernel-checked level-2 ladder acceptance.  No `native_decide`. -/"
    )
    lines.append("theorem ladder_accepts : checkCampaign record groups = true := by")
    lines.append("  rfl")
    lines.append("")
    lines.append(
        "/-- The aggregated window chain, given one imported refinement fact"
    )
    lines.append("per level-2 record. -/")
    lines.append("theorem ladder_windowChain")
    lines.append("    (commit : List WindowSummary → Digest)")
    lines.append("    (refines : ∀ group ∈ groups, GroupRefines commit group) :")
    lines.append("    ∃ windows : List WindowSummary,")
    lines.append("      windows.length = record.blockCount ∧")
    lines.append(
        "      WindowChainValid record.firstBlock record.lowerCount windows ∧"
    )
    lines.append("      slotSum windows = record.slots ∧")
    lines.append(
        "      record.lowerCount + slotSum windows = record.upperCount :="
    )
    lines.append("  campaign_windowChain commit ladder_accepts refines")
    lines.append("")
    lines.append("end %s" % module)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("records", help="binary level-2 record file")
    parser.add_argument("--root", required=True, help="campaign root, 64 hex chars")
    parser.add_argument(
        "--module", default="SparkInterval.Zeta.PT21LadderInstance"
    )
    parser.add_argument("--output", default="-")
    arguments = parser.parse_args()

    blob = pathlib.Path(arguments.records).read_bytes()
    records = decode(blob)
    check_chain(records)
    module = emit(records, arguments.module, arguments.root)
    if arguments.output == "-":
        sys.stdout.write(module)
    else:
        pathlib.Path(arguments.output).write_text(module)
    sys.stderr.write(
        "emitted %d level-2 records covering %d blocks\n"
        % (len(records), sum(record["blocks"] for record in records))
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
