#!/usr/bin/env python3
# Copyright (c) 2026 Gershon Bialer. All rights reserved.
# SPDX-License-Identifier: MIT

"""Generate the dstack deploy manifest for the CH25 A.7 Phala TDX campaign.

Two files come out:

* ``docker-compose.yaml`` -- two services, both pinned to the campaign image
  **by registry digest**.  The first is the prelude, which stages the inputs
  the entry point requires; the second is the campaign itself, which starts
  only if the prelude exited zero.
* ``app-compose.json`` -- the dstack application document.  Its ``sha256`` is
  the ``compose_hash`` dstack measures into RTMR3, and its first twenty bytes
  are the ``app_id``.

The prelude's Python source is embedded verbatim inside
``docker-compose.yaml``, and therefore inside ``app-compose.json``, and
therefore inside the compose hash and RTMR3.  That is the point: the code that
derives the key, computes the report-data commitment and gates on the
appraisal is measured by the same quote it requests.  It is not fetched at run
time and it is not baked into the image (the published image predates it).

``tests/test_phala_tdx_manifest.py`` re-runs this generator and requires the
committed files to match byte for byte, so the embedded copy cannot drift from
``proof_build/ch25_a7_phala_tdx/prelude_phala_tdx_inputs.py``.

Usage
-----

Committed template (challenge and job binding are refusal sentinels)::

    python3 tools/tg_phala_tdx_compose.py --template

A real deployment::

    python3 tools/tg_phala_tdx_compose.py \\
        --challenge <64 hex, unpredictable, chosen before the run> \\
        --job-binding <64 hex> \\
        --issued-at 2026-08-01T00:00:00Z \\
        --out-dir /somewhere/outside/the/repo
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
PRELUDE = ROOT / "proof_build/ch25_a7_phala_tdx/prelude_phala_tdx_inputs.py"
DEFAULT_OUT_DIR = ROOT / "proof_build/ch25_a7_phala_tdx"

IMAGE_DIGEST = (
    "sha256:4e6029a39771bd18f9e0b9bc64017393700ce47c17a678dd93cbf0ddc17c774f"
)
IMAGE = (
    "ghcr.io/gersh/sparkinterval-ch25-a7-phala-tdx@" + IMAGE_DIGEST
)

APP_NAME = "sparkinterval-ch25-a7-boundary"
HEREDOC = "SPARKINTERVAL_PRELUDE_SOURCE_EOF"

# Deliberately not 64 hex digits: `require_phala_tdx_worker` rejects these, so
# the committed template cannot be deployed by accident.
TEMPLATE_CHALLENGE = "REPLACE-WITH-64-HEX-UNPREDICTABLE-CHALLENGE-NONCE"
TEMPLATE_JOB_BINDING = "REPLACE-WITH-64-HEX-JOB-BINDING-SHA256"
TEMPLATE_ISSUED_AT = "REPLACE-WITH-RFC3339-UTC-INSTANT"

HEX64 = re.compile(r"\A[0-9a-f]{64}\Z")
RFC3339 = re.compile(r"\A\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\Z")


def indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "".join(pad + line if line.strip() else line for line in text.splitlines(True))


def compose_yaml(*, challenge: str, job_binding: str, issued_at: str,
                 IMAGE: str = IMAGE) -> str:
    # ``IMAGE`` overrides the registry host only.  The digest is not a
    # parameter: ``IMAGE_DIGEST`` stays authoritative and the caller is
    # required to supply a reference carrying exactly it, so a different
    # registry can never mean different bytes.
    if not IMAGE.endswith("@" + IMAGE_DIGEST):
        raise SystemExit(
            f"image reference must be pinned to {IMAGE_DIGEST}; got {IMAGE}"
        )
    prelude_source = PRELUDE.read_text(encoding="utf-8")
    if HEREDOC in prelude_source:
        raise SystemExit("the prelude source contains the heredoc sentinel")
    if "\t" in prelude_source:
        raise SystemExit("the prelude source contains a tab; YAML block scalars "
                         "and tabs do not mix")
    for number, line in enumerate(prelude_source.splitlines(), start=1):
        if line != line.rstrip():
            raise SystemExit(
                f"the prelude source has trailing whitespace on line {number}; "
                "a YAML block scalar would not round-trip it"
            )

    entrypoint = (
        f"cat >/tmp/prelude.py <<'{HEREDOC}'\n"
        + prelude_source
        + f"{HEREDOC}\n"
        "exec python3 /tmp/prelude.py \\\n"
        "  --input-root /workspace/staging/input \\\n"
        "  --evidence-root /workspace/retained/evidence\n"
    )

    campaign_entrypoint = (
        "set -a\n"
        ". /workspace/staging/input/job-scope.env\n"
        "set +a\n"
        "exec /opt/sparkinterval/run_phala_tdx_campaign.sh\n"
    )

    return f"""# Copyright (c) 2026 Gershon Bialer. All rights reserved.
# SPDX-License-Identifier: MIT
#
# GENERATED BY tools/tg_phala_tdx_compose.py -- DO NOT EDIT BY HAND.
# Regenerate with `python3 tools/tg_phala_tdx_compose.py --template`;
# tests/test_phala_tdx_manifest.py fails if this file drifts.
#
# dstack application for the CH25 Lemma A.7 boundary campaign in an Intel TDX
# confidential VM.  Two one-shot services:
#
#   prelude   derives the P-256 signing key from the dstack guest agent,
#             commits to its public key in the TDX quote's report data,
#             fetches the quote, appraises it with the pinned dcap-qvl against
#             the reviewed policy, stages the retained A.7 artifact, and
#             writes the seven files the campaign entry point requires.  It is
#             the only service that can reach the network or the dstack
#             socket.
#   campaign  the published image's own entry point.  It starts ONLY on
#             `service_completed_successfully`, so a failed appraisal is not
#             followed by a receipt.  No network, read-only root filesystem.
#
# The image is referenced by registry digest, never by a tag.
#
# The staging volume is a tmpfs: the derived signing key is written there and
# must never touch the CVM's disk.  The retained and output volumes are
# ordinary volumes so the evidence survives the containers and can be copied
# out before the CVM is destroyed.

services:
  prelude:
    image: {IMAGE}
    restart: "no"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - campaign-staging:/workspace/staging
      - campaign-retained:/workspace/retained
    environment:
      - SPARKINTERVAL_PHALA_TDX_WORKER_SCOPE=sparkinterval.phala-tdx-measured-worker.v1
      - SPARKINTERVAL_PHALA_TDX_WORKER_BACKEND=phala_dstack_tdx_cpu
      - SPARKINTERVAL_PHALA_TDX_WORKER_CHALLENGE_NONCE={challenge}
      - SPARKINTERVAL_PHALA_TDX_WORKER_JOB_BINDING_SHA256={job_binding}
      - TG_FINAL_IMAGE_REFERENCE={IMAGE_DIGEST}
      - TG_ISSUED_AT={issued_at}
      # Supplied as dstack encrypted environment, listed in allowed_envs.
      # They are deliberately NOT literals here: the appraisal policy pins
      # RTMR3, and RTMR3 is a function of these compose bytes, so a policy
      # embedded here could never be filled in.
      - TG_DCAP_QVL_POLICY_B64
      - TG_A7_ARTIFACT_URL
    entrypoint:
      - /bin/bash
      - -ec
      - |
{indent(entrypoint, 8)}
  campaign:
    image: {IMAGE}
    restart: "no"
    network_mode: none
    read_only: true
    depends_on:
      prelude:
        condition: service_completed_successfully
    volumes:
      - campaign-staging:/workspace/staging:ro
      - campaign-output:/workspace/out
    tmpfs:
      - /workspace/runtime:exec,size=64m
      - /tmp:size=16m
    environment:
      - SPARKINTERVAL_PHALA_TDX_WORKER_SCOPE=sparkinterval.phala-tdx-measured-worker.v1
      - SPARKINTERVAL_PHALA_TDX_WORKER_BACKEND=phala_dstack_tdx_cpu
      - SPARKINTERVAL_PHALA_TDX_WORKER_CHALLENGE_NONCE={challenge}
      - SPARKINTERVAL_PHALA_TDX_WORKER_JOB_BINDING_SHA256={job_binding}
      - TG_FINAL_IMAGE_REFERENCE={IMAGE_DIGEST}
      - TG_ISSUED_AT={issued_at}
      - TG_INPUT_ROOT=/workspace/staging/input
      - TG_OUTPUT_ROOT=/workspace/out/output
    entrypoint:
      - /bin/bash
      - -ec
      - |
{indent(campaign_entrypoint, 8)}
volumes:
  campaign-staging:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=512m,mode=0700
  campaign-retained: {{}}
  campaign-output: {{}}
"""


def app_compose(compose_text: str) -> str:
    """Serialize exactly the way dstack's own ``vmm-cli.py`` does.

    ``compose_hash`` is the SHA-256 of these raw bytes -- there is no
    canonicalization step anywhere in dstack -- so key order, indentation and
    the absence of a trailing newline all matter.  The key set and the
    ``json.dumps(indent=4, ensure_ascii=False)`` call below mirror
    ``vmm/src/vmm-cli.py::create_app_compose`` at dstack v0.5.3 so that a hash
    computed here and a hash computed by dstack's tooling agree.

    ``no_instance_id`` is true on purpose: it removes the per-instance random
    value from the RTMR3 chain, which is what makes RTMR3 a function of the
    app id and the compose hash alone and therefore pinnable at all.
    """

    document = {
        "manifest_version": 2,
        "name": APP_NAME,
        "runner": "docker-compose",
        "docker_compose_file": compose_text,
        "kms_enabled": True,
        "gateway_enabled": False,
        "local_key_provider_enabled": False,
        "key_provider_id": "",
        "public_logs": False,
        "public_sysinfo": False,
        "allowed_envs": ["TG_DCAP_QVL_POLICY_B64", "TG_A7_ARTIFACT_URL"],
        "no_instance_id": True,
        "secure_time": True,
    }
    return json.dumps(document, indent=4, ensure_ascii=False)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--challenge")
    parser.add_argument("--job-binding")
    parser.add_argument("--issued-at")
    parser.add_argument(
        "--template",
        action="store_true",
        help="emit the committed template, whose challenge and job binding "
        "are refusal sentinels rather than valid hexadecimal",
    )
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument(
        "--image",
        default=IMAGE,
        help="registry reference for the campaign image.  It must still be "
        f"pinned to {IMAGE_DIGEST}, so this changes only where the bytes are "
        "fetched from, never which bytes.  Use it when the default registry "
        "is not anonymously pullable by the CVM.",
    )
    parser.add_argument(
        "--print-only",
        action="store_true",
        help="write nothing; print the compose hash and app id",
    )
    args = parser.parse_args()

    if args.template:
        if args.challenge or args.job_binding or args.issued_at:
            parser.error("--template takes no challenge, binding or timestamp")
        challenge = TEMPLATE_CHALLENGE
        job_binding = TEMPLATE_JOB_BINDING
        issued_at = TEMPLATE_ISSUED_AT
    else:
        for name, value, pattern, shape in (
            ("--challenge", args.challenge, HEX64, "64 lowercase hex digits"),
            ("--job-binding", args.job_binding, HEX64, "64 lowercase hex digits"),
            ("--issued-at", args.issued_at, RFC3339, "an RFC 3339 UTC instant"),
        ):
            if not value or not pattern.match(value):
                parser.error(f"{name} must be {shape}")
        if args.challenge == args.job_binding:
            parser.error("--challenge and --job-binding must differ")
        challenge = args.challenge
        job_binding = args.job_binding
        issued_at = args.issued_at

    compose_text = compose_yaml(
        challenge=challenge, job_binding=job_binding, issued_at=issued_at,
        IMAGE=args.image,
    )
    document = app_compose(compose_text)
    compose_hash = hashlib.sha256(document.encode("utf-8")).hexdigest()

    if not args.print_only:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        (args.out_dir / "docker-compose.yaml").write_text(
            compose_text, encoding="utf-8"
        )
        (args.out_dir / "app-compose.json").write_text(document, encoding="utf-8")

    print(f"app-compose.json sha256 (compose_hash) : {compose_hash}")
    print(f"app id (first 20 bytes)                : {compose_hash[:40]}")
    print(f"image                                  : {args.image}")
    if args.template:
        print(
            "TEMPLATE: the challenge and job binding are refusal sentinels; "
            "the campaign guard rejects them."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
